### ISSUE TITLE
1.15.2(Fabric with Optfine) When i opened the Area Selection Browser, the game crashed:(

### ISSUE THREAD

**Issue by vae9696** [maruohon/litematica#112]
My game verison is 1.15.2 (Fabric with Optfine)
I Install malilib and not open the render regions, fast render etc.
but when i opened the Area Selection Browser(and some options),my game crashed :(
I am Chinese so i don't really understand about these english crash reort.
 (I know ,my grammer and words is suck)
Here is the crash reoprt:

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 20年2月20日 下午6:54
Description: Rendering screen

java.lang.NoSuchMethodError: net.minecraft.class_4587.method_22910()Lnet/minecraft/class_1159;
	at fi.dy.masa.malilib.render.RenderUtils.drawHoverText(RenderUtils.java:274)
	at fi.dy.masa.litematica.gui.widgets.WidgetAreaSelectionEntry.postRenderHovered(WidgetAreaSelectionEntry.java:131)
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.drawContents(WidgetListBase.java:435)
	at fi.dy.masa.malilib.gui.widgets.WidgetFileBrowserBase.drawContents(WidgetFileBrowserBase.java:81)
	at fi.dy.masa.malilib.gui.GuiListBase.drawContents(GuiListBase.java:177)
	at fi.dy.masa.malilib.gui.GuiBase.render(GuiBase.java:163)
	at net.minecraft.class_757.method_3192(class_757.java:789)
	at net.minecraft.class_310.method_1523(class_310.java:989)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fi.dy.masa.malilib.render.RenderUtils.drawHoverText(RenderUtils.java:274)
	at fi.dy.masa.litematica.gui.widgets.WidgetAreaSelectionEntry.postRenderHovered(WidgetAreaSelectionEntry.java:131)
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.drawContents(WidgetListBase.java:435)
	at fi.dy.masa.malilib.gui.widgets.WidgetFileBrowserBase.drawContents(WidgetFileBrowserBase.java:81)
	at fi.dy.masa.malilib.gui.GuiListBase.drawContents(GuiListBase.java:177)
	at fi.dy.masa.malilib.gui.GuiBase.render(GuiBase.java:163)

-- Screen render details --
Details:
	Screen name: fi.dy.masa.litematica.gui.GuiAreaSelectionManager
	Mouse location: Scaled: (238, 89). Absolute: (476.000000, 179.000000)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['vae9696'/36, l='MpServer', x=-232.63, y=93.56, z=134.90]]
	Chunk stats: Client Chunk Cache: 1225, 841
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: -1471492063929413441
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-216,-1,136), Chunk: (at 8,-1,8 in -14,8; contains blocks -224,0,128 to -209,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 221338 game time, 9151 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:611)
	at net.minecraft.class_310.method_1587(class_310.java:1921)
	at net.minecraft.class_310.method_1514(class_310.java:634)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 869398744 bytes (829 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 1.2.4
		cloth-config2: Cloth Config v2 2.4-unstable.201911031154
		fabric: Fabric API 0.4.32+build.292-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.2.4+203491ea0c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.7+a1bd31180c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d0c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d0c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed90c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104900c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabricloader: Fabric Loader 0.7.8+build.184
		inventoryprofiles: Inventory Profiles 0.1.0-dev.6
		litematica: Litematica 0.0.0-dev.20200212.174750
		malilib: MaLiLib 0.10.0-dev.20
		minecraft: Minecraft 1.15.2
		mm: Manningham Mills 2.0
		modmenu: Mod Menu 1.10.1+build.30
		optifabric: Optifabric 1.0.0-beta4
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		shulkerboxtooltip: Shulker Box Tootip 1.4.5+1.15
		voxelmap: VoxelMap 1.9.14
	Launched Version: fabric-loader-0.7.8+build.184-1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 436.15, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre5
	OptiFine Build: 20200219-183028
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 436.15
	OpenGlRenderer: GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by vae9696** [comment]
I want to add some images about the details , but i don't find it :(

**Comment by vae9696** [comment]
i try to no use optfine,just use fabric verison to use litematica, but it still like that,game crashed again:D

**Comment by maruohon** [comment]
Did you get the correct latest version of malilib for 1.15.2?

**Comment by vae9696** [comment]
> Did you get the correct latest version of malilib for 1.15.2?

Oh,it work now after I download the malilib again, it's maybe I missed the new version, thx your advice, it's really helpful
