### ISSUE TITLE
Fabric 1.15.2 not working

### ISSUE THREAD

**Issue by nateeeeeeee** [maruohon/litematica#124]
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: fabric requires {minecraft @ [~1.15-alpha.19.42.a]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:170)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:603)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:176)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:166)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:168)
	... 5 more

(yes i have the fabric api and malilib)

**Comment by maruohon** [comment]
You seem to have downloaded the Fabric API mod for snapshot 19w42a?
Also my mods don't need the Fabric API at all, so you can remove it unless you have other mods that need it.

**Comment by nateeeeeeee** [comment]
i have immersive portals and worldedit

**Comment by nateeeeeeee** [comment]
and light overlay

**Comment by maruohon** [comment]
Then get the 1.15.2 version of Fabric API.

So either this: https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/2898702
or this: https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/2879020
depending on which version your other mods need/work with.

**Comment by nateeeeeeee** [comment]
so i downloaded the 1.15.2 version of fabric api from curseforge and it gave me the 1.14.4

**Comment by nateeeeeeee** [comment]
so it turns out that i not only downloaded the fabric api for 1.14.4, i was also using fabric 1.14.4 to try and run 1.15 mods. I think my problem is solved, maybe.

**Comment by nateeeeeeee** [comment]
it is
