### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by nitram9876** [maruohon/litematica#135]
Hi, I have installed rift for 1.13.2, put litematica and malilib for 1.13.2 in the mods folder but every time I try to launch it, it crashes. 
Here is the latest log.
```
[14:17:19] [main/INFO]: Loading tweak class name org.dimdev.riftloader.launch.RiftLoaderClientTweaker
[14:17:19] [main/INFO]: Using primary tweak class name org.dimdev.riftloader.launch.RiftLoaderClientTweaker
[14:17:19] [main/INFO]: Calling tweak class org.dimdev.riftloader.launch.RiftLoaderClientTweaker
[14:17:19] [main/INFO]: Searching mods on classpath
[14:17:20] [main/INFO]: Loaded mod 'rift'
[14:17:20] [main/INFO]: Searching for mods in C:\Users\Martin\AppData\Roaming\.minecraft\mods
[14:17:20] [main/INFO]: Loaded mod 'litematica'
[14:17:20] [main/INFO]: Loaded mod 'malilib'
[14:17:20] [main/INFO]: Loaded 3 mods
[14:17:20] [main/INFO]: Initializing mods
[14:17:20] [main/INFO]: Loading Rift!
[14:17:20] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/Martin/AppData/Roaming/.minecraft/libraries/org/dimdev/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
[14:17:20] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[14:17:20] [main/INFO]: Compatibility level set to JAVA_8
[14:17:20] [main/INFO]: Adding new token provider org.dimdev.rift.Rift$RiftTokens to MixinEnvironment[DEFAULT]
[14:17:20] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:28) ~[Rift-jitpack-aeee80c1fb-1.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26) ~[Rift-jitpack-aeee80c1fb-1.jar:?]
	... 2 more
Caused by: java.lang.NoSuchMethodError: fi.dy.masa.malilib.event.InitializationHandler.getInstance()Lfi/dy/masa/malilib/event/InitializationHandler;
	at fi.dy.masa.litematica.Litematica.onInitialization(Litematica.java:33) ~[litematica-rift-1.13.2-0.0.0-dev.20190203.221737.jar:?]
	at org.dimdev.riftloader.RiftLoader.initMods(RiftLoader.java:196) ~[Rift-jitpack-aeee80c1fb-1.jar:?]
	at org.dimdev.riftloader.RiftLoader.load(RiftLoader.java:55) ~[Rift-jitpack-aeee80c1fb-1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26) ~[Rift-jitpack-aeee80c1fb-1.jar:?]
	... 2 more
```

**Comment by vacla** [comment]
Update malilib to latest version, on cf it is marked as beta

**Comment by nitram9876** [comment]
> Update malilib to latest version, on cf it is marked as beta

Hi, I can't find any version of malilib for 1.13.2 that's beta, the latest one I could find is malilib-rift-1.13.2-0.10.0-dev.19.jar which I have installed.

**Comment by vacla** [comment]
ah, you need to update Litematica then to latest version from 20190611

**Comment by nitram9876** [comment]
@vacla Thank you! now it works perfectly 😄
