### ISSUE TITLE
it's trying to access which way a brewing stand is facing, which isn't a thing

### ISSUE THREAD

**Issue by Azutte** [maruohon/litematica#17]
https://cdn.discordapp.com/attachments/469978950731431946/536750753881260033/unknown.png

This seems to have happened when I tried alt-scrolling a schematic with a brewing stand in it, but the schematic was *rotated*. On client reload it seems to be fine with me just letting the schematic sit there, but when I alt-scroll it some more, it does the same crash.
 
![2019-01-20_19 40 37](https://user-images.githubusercontent.com/6581284/51451692-54604b80-1ceb-11e9-9d25-86639131a71c.png)

**Comment by Azutte** [comment]
https://pastebin.com/733UDqPN crash report

**Comment by maruohon** [comment]
Can you upload that schematic? It would probably make it a bit easier to reproduce, as there is probably some block with a rotation next to a brewing stand. Seems like the renderer is probably seeing an old TileEntity that was removed from the world but the renderer is lagging behind by one frame/tick, or something like that.

**Comment by Azutte** [comment]
oops! This is what I get for disabling email notifications. [Here.](https://cdn.discordapp.com/attachments/469978950731431946/536732265917579267/r23_house_v1.litematic) tell me if that one doesn't work,

**Comment by SunSerega** [comment]
Ok, i can confirm. After Alt+Scrolling for, like, 2 min's a got this:

[latest.log](https://github.com/maruohon/litematica/files/2928205/latest.log)

I was using 1.13.2, super flat void, at doing it around coordinates, with same rotation and mirror mode that i see on that screenshot.

Error from log file:
```
[23:10:50] [main/FATAL]: Reported exception thrown!
h: Rendering Block Entity
	at cwa.a(TileEntityRendererDispatcher.java:214) ~[cwa.class:?]
	at cwa.a(TileEntityRendererDispatcher.java:156) ~[cwa.class:?]
	at fi.dy.masa.litematica.render.schematic.WorldRendererSchematic.a(WorldRendererSchematic.java:808) ~[WorldRendererSchematic.class:?]
	at fi.dy.masa.litematica.render.LitematicaRenderer.renderWorld(LitematicaRenderer.java:164) ~[LitematicaRenderer.class:?]
	at fi.dy.masa.litematica.render.LitematicaRenderer.renderSchematicWorld(LitematicaRenderer.java:69) ~[LitematicaRenderer.class:?]
	at fi.dy.masa.litematica.event.RenderHandler.onRenderWorldLast(RenderHandler.java:25) ~[RenderHandler.class:?]
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderWorldLast(RenderEventHandler.java:61) ~[RenderEventHandler.class:?]
	at cty.handler$onRenderWorldLast$zcj000(EntityRenderer.java:2400) ~[cty.class:?]
	at cty.b(EntityRenderer.java:1547) ~[cty.class:?]
	at cty.a(EntityRenderer.java:1217) ~[cty.class:?]
	at cty.a(EntityRenderer.java:979) ~[cty.class:?]
	at cft.c(SourceFile:850) ~[cft.class:?]
	at cft.a(SourceFile:395) [cft.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalArgumentException: Cannot get property bmh{name=part, clazz=class blz, values=[head, foot]} as it does not exist in Block{minecraft:ender_chest}
	at bla.c(SourceFile:95) ~[bla.class:?]
	at cvz.a(SourceFile:40) ~[cvz.class:?]
	at cvz.a(SourceFile:17) ~[cvz.class:?]
	at cwa.a(TileEntityRendererDispatcher.java:205) ~[cwa.class:?]
	... 19 more
```
So, this time it's trying to get bed propertyes of enter chest.

**Comment by SunSerega** [comment]
Oh, also, i forgot there are actual crash reports, not just logs. Here:

[crash-2019-03-04_23.10.50-client.txt](https://github.com/maruohon/litematica/files/2928301/crash-2019-03-04_23.10.50-client.txt)

**Comment by maruohon** [comment]
This should be fixed in the latest builds.
