### ISSUE TITLE
Crash in Multiplayer servers with BotFilter

### ISSUE THREAD

**Issue by MaelstromDota** [maruohon/litematica#262]
**Minecraft version**
1.16.4 fabric 0.10.6 build 214

**Mod version and malilib version**
litematica-fabric-1.16.4-0.0.0-dev.20201103.184101
malilib-fabric-1.16.4-0.10.0-dev.21+arne.1

**Description of the bug**
Crash

---

**Expected behavior**
I can play without crash

**To Reproduce**
1. Go to multiplayer server with botfilter (falling test)
2. Wait a few seconds
3. Minecraft crash

**Screenshots**

**Additional context**

> ---- Minecraft Crash Report ----
> // I bet Cylons wouldn't have this problem.
> 
> Time: 14.11.20 1:40
> Description: Unexpected error
> 
> java.lang.NullPointerException: Unexpected error
> 	at fi.dy.masa.litematica.render.schematic.WorldRendererSchematic.setupTerrain(WorldRendererSchematic.java:218)
> 	at fi.dy.masa.litematica.render.LitematicaRenderer.piecewisePrepareAndUpdate(LitematicaRenderer.java:321)
> 	at net.minecraft.class_761.handler$bbh000$onPostSetupTerrain(class_761.java:6115)
> 	at net.minecraft.class_761.method_3273(class_761.java:1401)
> 	at net.minecraft.class_761.method_22710(class_761.java:1552)
> 	at net.minecraft.class_757.method_3188(class_757.java:1022)
> 	at net.minecraft.class_757.method_3192(class_757.java:693)
> 	at net.minecraft.class_310.method_1523(class_310.java:1048)
> 	at net.minecraft.class_310.method_1514(class_310.java:681)
> 	at net.minecraft.client.main.Main.main(Main.java:215)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at fi.dy.masa.litematica.render.schematic.WorldRendererSchematic.setupTerrain(WorldRendererSchematic.java:218)
> 	at fi.dy.masa.litematica.render.LitematicaRenderer.piecewisePrepareAndUpdate(LitematicaRenderer.java:321)
> 	at net.minecraft.class_761.handler$bbh000$onPostSetupTerrain(class_761.java:6115)
> 	at net.minecraft.class_761.method_3273(class_761.java:1401)
> 	at net.minecraft.class_761.method_22710(class_761.java:1552)
> 	at net.minecraft.class_757.method_3188(class_757.java:1022)
> 
> -- OptiFabric --
> Details:
> 	OptiFine jar designed for: 1.16.4
> 	OptiFine jar version: OptiFine_1.16.4_HD_U_G5
> 	OptiFine jar status: Valid OptiFine installer
> 	OptiFine remapped jar: C:\Users\Maelstrom\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.4_HD_U_G5\Optifine-mapped.jar
> 	OptiFabric error: <None>
> Stacktrace:
> 	at net.minecraft.class_128.handler$zci000$fillSystemDetails(class_128.java:523)
> 	at net.minecraft.class_128.<init>(class_128.java:55)
> 	at net.minecraft.class_310.method_1514(class_310.java:704)
> 	at net.minecraft.client.main.Main.main(Main.java:215)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
> 
> -- Affected level --
> Details:
> 	All players: 1 total; [class_746['MaelstromDota'/2075221956, l='ClientLevel', x=7.00, y=450.00, z=7.00]]
> 	Chunk stats: Client Chunk Cache: 121, 1
> 	Level dimension: minecraft:overworld
> 	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
> 	Level time: 1 game time, 23700 day time
> 	Server brand: BotFilter (https://vk.cc/8hr1pU)
> 	Server type: Non-integrated multiplayer server

**Comment by maruohon** [comment]
Does this happen every time when logging in to that server?
Does this only happen on "BotFilter" servers? And not in single player for example?

**Comment by MaelstromDota** [comment]
1) Yes
2) Only servers with "BotFilter", single player, or any server without "BotFilter"

**Comment by maruohon** [comment]
> Only servers with "BotFilter", single player, or any server without "BotFilter"

Hmm what, so "only everywhere"?

If it happens in every world, then what other mods do you have? Something must be breaking the renderer initialization or the schematic world creation.

**Comment by MaelstromDota** [comment]
> > Only servers with "BotFilter", single player, or any server without "BotFilter"
> 
> Hmm what, so "only everywhere"?
> 
> If it happens in every world, then what other mods do you have? Something must be breaking the renderer initialization or the schematic world creation.

Oh, I'm wrong, single player or any server without "BotFilter" doesn't crash

**Comment by MaelstromDota** [comment]
Crash only when BotFilter does falling check, when it successfully check it (only with optifine) and connecting to server (with all mods) game will not crash (BotFilter doesn't check, because it checked me in last 24h)
