### ISSUE TITLE
Crash to desktop when joining a server.

### ISSUE THREAD

**Issue by Souls2** [maruohon/litematica#345]
When I join a server with litematica and malilib installed, it tries to load the world normally but crashes to desktop immediately after.

[crash-2021-05-23_00.10.06-client.txt](https://github.com/maruohon/litematica/files/6527561/crash-2021-05-23_00.10.06-client.txt)

**Comment by maruohon** [comment]
Looks like it actually crashes via Optifine:
```
java.lang.NullPointerException: Unexpected error
	at net.optifine.CustomColors.getWorldSkyColor(CustomColors.java:1541)
	at net.minecraft.class_758.method_3210(class_758.java:89)
	at com.mamiyaotaru.voxelmap.Map.getSkyColor(Map.java:1037)
	at com.mamiyaotaru.voxelmap.Map.calculateCurrentLightAndSkyColor(Map.java:1008)
```

However I don't know why it would only happen with Litematica present... I would think VoxelMap should not be trying to do anything with the schematic world, and I don't see Litematica stuff in the stack trace.

Is it possible to somehow disable that custom sky color stuff from Optifine?

**Comment by maruohon** [comment]
Since this crash does not happen to everyone using Litematica + VoxelMap + Optifine, I think it may be related to some resource pack feature involving custom sky textures or colors or whatever Optifine provides there. If you have some kind of (sky) resource pack active, try if disabling it fixes the crash.

**Comment by Souls2** [comment]
> Looks like it actually crashes via Optifine:
> 
> ```
> java.lang.NullPointerException: Unexpected error
> 	at net.optifine.CustomColors.getWorldSkyColor(CustomColors.java:1541)
> 	at net.minecraft.class_758.method_3210(class_758.java:89)
> 	at com.mamiyaotaru.voxelmap.Map.getSkyColor(Map.java:1037)
> 	at com.mamiyaotaru.voxelmap.Map.calculateCurrentLightAndSkyColor(Map.java:1008)
> ```
> 
> However I don't know why it would only happen with Litematica present... I would think VoxelMap should not be trying to do anything with the schematic world, and I don't see Litematica stuff in the stack trace.
> 
> Is it possible to somehow disable that custom sky color stuff from Optifine?

Well without voxelmap in the mods folder it worked great, I could load schematics and play the server just fine, but I disabled custom sky in the optifine settings, then installed a version of voxelmap that my friend uses (he has just about the same mods I do but with different versions, he never crashes), and now I'm back to crashing and getting the same error.
![Capture](https://user-images.githubusercontent.com/28557421/119274124-0964e480-bbd4-11eb-83b5-aca6e34d73b7.PNG)

**Comment by Souls2** [comment]
> Since this crash does not happen to everyone using Litematica + VoxelMap + Optifine, I think it may be related to some resource pack feature involving custom sky textures or colors or whatever Optifine provides there. If you have some kind of (sky) resource pack active, try if disabling it fixes the crash.

I'm using the default texture pack with no shaders on a completely fresh install of minecraft, so far the only thing that's different from being able to play just fine with no problems and crashing to desktop is whether or not I have voxelmap installed. I uninstall it and everything works great, I even installed xaero's minimap and it's loading perfectly fine.
