### ISSUE TITLE
[1.14.2 - Fabric] Crash log

### ISSUE THREAD

**Issue by IcyTower1337** [maruohon/litematica#42]
Just tried using the fabric 1.14.2 build on your website, but it throws out this error and doesn't start, thought it would help to post the log:

```
16:38:56
launcher
main
info
Preparing to launch minecraft client for fabric-loader-0.4.8+build.155-1.14.2
16:38:57
launcher
main
info
Checking installations.
16:38:57
launcher
main
info
Minecraft client fabric-loader-0.4.8+build.155-1.14.2 is ready to start.
16:38:57
launcher
main
info
Starting!
16:38:57
launcher
main
info
Using default game log configuration client-1.12.xml (outputs XML)
16:38:58
FabricLoader
main
info
Loading for game Minecraft 1.14.2
16:39:09
launcher
main
info

 Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!
 at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:147)
 at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:120)
 at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
 Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: litematica requires {malilib @ [>=0.10.0-dev.19]})
 at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:185)
 at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:483)
 at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:145)
 ... 2 more
 Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
 at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
 at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
 at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
 at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
 at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
 ... 4 more
16:39:09
monitor
Process Monitor
fatal
Process crashed with exit code 1```

**Comment by vacla** [comment]
is it possible to put the latest.log in https://pastebin.com and a screenshot of all mods in your mods folder?

**Comment by IcyTower1337** [comment]
That's one of the issues, the latest.log only spits out this:
https://pastebin.com/MVmitKp4

I had to use the "Open output log when the game starts" to get the information above, I'm only showing the fatal and info's, theres about 6338 debugs that I hid so the log i posted above wouldn't be too long, but I'll post that here:
https://pastebin.com/qtJrsKsW 

Regarding the mods I currently have, I removed every mod that I had installed as to remove any chance of it being a conflict between mods so I only have these:
https://puu.sh/DHbYi/b5929325f2.png

**Comment by maruohon** [comment]
You seem to be missing malilib.

**Comment by IcyTower1337** [comment]
Yep, that was totally my issue. My mistake thought it was just an issue with it being a beta build. Apologies!
