### ISSUE TITLE
Game crashes on opening world/joining world with only mods litematica & malilib

### ISSUE THREAD

**Issue by Exzellius** [maruohon/litematica#475]
* **Minecraft version** - 1.18
* **Mod version and malilib version** - litematica-fabric-1.18.0-0.9.0.jar & malilib-fabric-1.18.0-0.10.0-dev.26.jar
* **A clear description of the issue** - 
game crashes with an error (see below) when using litematica, if I remove litematica, game works fine
here is the error log:
MultiMC version: 0.6.14-3001

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.66.179.68]

session.minecraft.net resolves to:
    [52.21.65.46, 3.213.200.53, 34.205.58.168]

textures.minecraft.net resolves to:
    [13.227.133.83, 13.227.133.13, 13.227.133.50, 13.227.133.11]

api.mojang.com resolves to:
    [99.84.93.121]

Minecraft folder is:
I:/Spiele/MultiMC/instances/1.18 (Exzellius)/.minecraft

Java path is:
C:/Program Files/Java/jdk-17.0.1/bin/javaw.exe

Checking Java version...
Java is version 17.0.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  I:/Spiele/MultiMC/instances/1.18 (Exzellius)/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  I:/Spiele/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  I:/Spiele/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  I:/Spiele/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  I:/Spiele/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  I:/Spiele/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  I:/Spiele/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  I:/Spiele/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  I:/Spiele/MultiMC/libraries/com/mojang/blocklist/1.0.6/blocklist-1.0.6.jar
  I:/Spiele/MultiMC/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  I:/Spiele/MultiMC/libraries/com/github/oshi/oshi-core/5.8.2/oshi-core-5.8.2.jar
  I:/Spiele/MultiMC/libraries/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar
  I:/Spiele/MultiMC/libraries/net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar
  I:/Spiele/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  I:/Spiele/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  I:/Spiele/MultiMC/libraries/com/ibm/icu/icu4j/69.1/icu4j-69.1.jar
  I:/Spiele/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  I:/Spiele/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  I:/Spiele/MultiMC/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  I:/Spiele/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  I:/Spiele/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  I:/Spiele/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  I:/Spiele/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  I:/Spiele/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  I:/Spiele/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  I:/Spiele/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  I:/Spiele/MultiMC/libraries/com/google/code/gson/gson/2.8.8/gson-2.8.8.jar
  I:/Spiele/MultiMC/libraries/com/mojang/authlib/3.2.38/authlib-3.2.38.jar
  I:/Spiele/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  I:/Spiele/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  I:/Spiele/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  I:/Spiele/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  I:/Spiele/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  I:/Spiele/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  I:/Spiele/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  I:/Spiele/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  I:/Spiele/MultiMC/libraries/net/fabricmc/intermediary/1.18.1/intermediary-1.18.1.jar
  I:/Spiele/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  I:/Spiele/MultiMC/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar
  I:/Spiele/MultiMC/libraries/net/fabricmc/tiny-remapper/0.6.0/tiny-remapper-0.6.0.jar
  I:/Spiele/MultiMC/libraries/net/fabricmc/access-widener/2.0.1/access-widener-2.0.1.jar
  I:/Spiele/MultiMC/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
  I:/Spiele/MultiMC/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
  I:/Spiele/MultiMC/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
  I:/Spiele/MultiMC/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
  I:/Spiele/MultiMC/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
  I:/Spiele/MultiMC/libraries/net/fabricmc/fabric-loader/0.12.12/fabric-loader-0.12.12.jar
  I:/Spiele/MultiMC/libraries/com/mojang/minecraft/1.18/minecraft-1.18-client.jar

Native libraries:
  I:/Spiele/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  I:/Spiele/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  I:/Spiele/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  I:/Spiele/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  I:/Spiele/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  I:/Spiele/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  I:/Spiele/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  I:/Spiele/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [📁] deactivated (folder)
  [✔️] litematica-fabric-1.18.0-0.9.0
  [✔️] malilib-fabric-1.18.0-0.10.0-dev.26

Params:
  --username  --version MultiMC5 --gameDir I:/Spiele/MultiMC/instances/1.18 (Exzellius)/.minecraft --assetsDir I:/Spiele/MultiMC/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 10660

Using onesix launcher.

[23:10:36] [main/INFO]: Loading Minecraft 1.18 with Fabric Loader 0.12.12
[23:10:36] [main/INFO]: Loading 6 mods:
	- fabric-resource-loader-v0 0.4.11+3ac43d9514 via malilib
	- fabricloader 0.12.12
	- java 17
	- litematica 0.9.0
	- malilib 0.10.0-dev.26
	- minecraft 1.18
[23:10:36] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/I:/Spiele/MultiMC/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[23:10:36] [main/INFO]: Compatibility level set to JAVA_16
[23:10:39] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:10:40] [Render thread/INFO]: Setting user: Exzellius
[23:10:41] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[23:10:44] [Render thread/INFO]: Narrator library for x64 successfully loaded
[23:10:44] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Resource Loader (v0), Fabric Loader, Litematica, MaLiLib)
[23:10:44] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[23:10:44] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[23:10:44] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[23:10:44] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[23:10:44] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[23:10:44] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[23:10:44] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[23:10:44] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[23:10:47] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Headphones (HyperX QuadCast S)
[23:10:47] [Render thread/INFO]: Sound engine started
[23:10:47] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[23:10:47] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[23:10:47] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[23:10:47] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[23:10:47] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[23:10:47] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[23:10:47] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[23:10:48] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[23:10:48] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[23:10:48] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[23:15:39] [Render thread/INFO]: Connecting to 5.83.172.181, 10010
[23:15:43] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:15:43] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:15:43] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[23:15:43] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[23:15:43] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:15:43] [Render thread/INFO]: Reloading ResourceManager: Default, mural.zip
[23:15:43] [Render thread/INFO]: Loaded 7 recipes
[23:15:43] [Render thread/INFO]: Loaded 1141 advancements
[23:15:43] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:15:43] [Server thread/INFO]: Starting integrated minecraft server version 1.18
[23:15:43] [Server thread/INFO]: Generating keypair
[23:15:44] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[23:15:44] [Render thread/INFO]: Preparing spawn area: 0%
[23:15:44] [Render thread/INFO]: Preparing spawn area: 0%
[23:15:45] [Render thread/INFO]: Preparing spawn area: 5%
[23:15:45] [Render thread/INFO]: Preparing spawn area: 55%
[23:15:45] [Render thread/INFO]: Time elapsed: 1803 ms
[23:15:45] [Server thread/INFO]: Changing view distance to 20, from 10
[23:15:45] [Server thread/INFO]: Changing simulation distance to 20, from 0
[23:15:46] [Server thread/INFO]: Exzellius[local:E:ab9fec87] logged in with entity id 5 at (-33.05933090356331, 224.0, -420.0261907579657)
[23:15:46] [Server thread/INFO]: Exzellius joined the game
[23:15:46] [Render thread/INFO]: Using 3 total BufferBuilder caches
[23:15:47] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NoSuchFieldError: field_29482
	at fi.dy.masa.litematica.render.schematic.WorldRendererSchematic.renderBlockLayer(WorldRendererSchematic.java:485) ~[litematica-fabric-1.18.0-0.9.0.jar:?]
	at fi.dy.masa.litematica.render.LitematicaRenderer.piecewiseRenderSolid(LitematicaRenderer.java:285) ~[litematica-fabric-1.18.0-0.9.0.jar:?]
	at net.minecraft.class_761.handler$zbd000$onRenderLayer(class_761.java:3910) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_3251(class_761.java:1703) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1259) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1026) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:810) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1117) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[23:15:47] [Server thread/INFO]: Stopping server
[23:15:47] [Server thread/INFO]: Saving players
[23:15:47] [Server thread/INFO]: Exzellius lost connection: Disconnected
[23:15:47] [Server thread/INFO]: Exzellius left the game
[23:15:47] [Server thread/INFO]: Stopping singleplayer server as player logged out
[23:15:47] [Server thread/INFO]: Saving worlds
[23:15:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Creative]'/minecraft:overworld
[23:15:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Creative]'/minecraft:the_nether
[23:15:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Creative]'/minecraft:the_end
[23:15:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (Creative): All chunks are saved
[23:15:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[23:15:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[23:15:48] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
---- Minecraft Crash Report ----
// Don't do that.

Time: 10/01/2022, 23:15
Description: Unexpected error

java.lang.NoSuchFieldError: field_29482
	at fi.dy.masa.litematica.render.schematic.WorldRendererSchematic.renderBlockLayer(WorldRendererSchematic.java:485)
	at fi.dy.masa.litematica.render.LitematicaRenderer.piecewiseRenderSolid(LitematicaRenderer.java:285)
	at net.minecraft.class_761.handler$zbd000$onRenderLayer(class_761.java:3910)
	at net.minecraft.class_761.method_3251(class_761.java:1703)
	at net.minecraft.class_761.method_22710(class_761.java:1259)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fi.dy.masa.litematica.render.schematic.WorldRendererSchematic.renderBlockLayer(WorldRendererSchematic.java:485)
	at fi.dy.masa.litematica.render.LitematicaRenderer.piecewiseRenderSolid(LitematicaRenderer.java:285)
	at net.minecraft.class_761.handler$zbd000$onRenderLayer(class_761.java:3910)
	at net.minecraft.class_761.method_3251(class_761.java:1703)
	at net.minecraft.class_761.method_22710(class_761.java:1259)
	at net.minecraft.class_757.method_3188(class_757.java:1026)

-- Affected level --
Details:
	All players: 1 total; [class_746['Exzellius'/5, l='ClientLevel', x=-33.06, y=224.00, z=-420.03]]
	Chunk stats: 2209, 443
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,55,8), Section: (at 8,7,8 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 106977 game time, 6000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2078380544 bytes (1982 MiB) / 3288334336 bytes (3136 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3,80
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 5700 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: DriverVersion=30.0.14011.3017
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23989,73
	Virtual memory used (MB): 16631,88
	Swap memory total (MB): 7680,00
	Swap memory used (MB): 143,25
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon RX 5700 XT GL version 3.2.14802 Core Profile Forward-Compatible Context 21.12.1 30.0.14011.3017, ATI Technologies Inc.
	Window size: 2498x1417
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 5800X 8-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['Exzellius'/5, l='ServerLevel[Creative]', x=-33.06, y=224.00, z=-420.03]]
	Data Packs: vanilla, file/mural.zip
#@!@# Game crashed! Crash report saved to: #@!@# I:\Spiele\MultiMC\instances\1.18 (Exzellius)\.minecraft\crash-reports\crash-2022-01-10_23.15.49-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.

anything else that could be helpful?

**Comment by maruohon** [comment]
This is a very strange crash to get, when the game version and the mod versions all match, and if there isn't even something like Optifine messing around with things. Usually this type of crash would happen if you were to try to use a mod made for a different Minecraft version.

When did you first create this instance, and also first install MC 1.18 via MultiMC? And also when did you first install Fabric to any 1.18 instance via MultiMC? Although I don't think there were any re-uploaded fixed Yarn intermediary mappings with 1.18, so it *probably* shouldn't matter...

The only thing I can think of to try to fix this, is to delete the `.fabric` directory from within the instance's `.minecraft` directory, and also to delete the `net/fabricmc` directory and perhaps also the directory where the vanilla game jar is within the `libraries` directory of the MultiMC installation, and let it re-download those. I don't remember off the top of my head which directory the vanilla stuff is in, it's either `net/minecraft` or `com/mojang` I think. Basically delete those so that he jars get re-downloaded in case they are somehow corrupted, and then let Fabric re-setup the remapped game jar (which I think goes to the `.fabric` directory within the instance directory).

Another thing you could try (unless you specifically need 1.18.0 for something) is to just remove the Fabric loader from the Versions tab in the instance settings, switch the game version to 1.18.1 and then add Fabric loader back. All of my client mods work in both 1.18.0 and 1.18.1 with the same current versions/files.

**Comment by Exzellius** [comment]
Yeah I removed all other mods for the test, normally I have Optifine, MiniHUD and Tweakeroo running with that.
I can test this when I get home from work this evening, thanks for the quick reply.

**Comment by maruohon** [comment]
Well MiniHUD and Tweakeroo certainly do work just fine with Litematica. And last I heard Optifine also just messes up some rendering things but shouldn't crash the game, but this is always a subject to change, so certainly a good idea to always test without Optifine at least.

**Comment by Exzellius** [comment]
So that didn't work, which is just curious.
Got the same error as before:
`java.lang.NoSuchFieldError: field_29482`
What I did to fix it:
deleted <MULTIMC-INSTALL-PATH>\instances\<INSTANCE-NAME>\.minecraft\.fabric
deleted <MULTIMC-INSTALL-PATH>\libraries\net\fabricmc
deleted <MULTIMC-INSTALL-PATH>\libraries\com\mojang
deleted fabric from the instance via the GUI
started the instance without fabric and loaded a world successfully
installed fabric again via the GUI
started the instance with fabric but without litematica and malilib and loaded a world successfully
installed (speak put .jar-files into <MULTIMC-INSTALL-PATH>\instances\<INSTANCE-NAME>\.minecraft\mods) litematica and malilib
started the instance and tried to load a world but got the same error as before

I will try to create a fresh instance with 1.18 next and try with that

**Comment by Exzellius** [comment]
with a new fresh instance it works ... I'll test to set all my settings and test periodically if it works still, I'll keep you updated on my findings

**Comment by Exzellius** [comment]
so I applied every setting I had on my old instance manually to the new and it just works ..
seems my old instance was somehow corrupt or something
it works now, so case closed
thank you again for your support
