### ISSUE TITLE
When I try to paste the schematic on the server, the client crash

### ISSUE THREAD

**Issue by monsters-97** [maruohon/litematica#503]
minecraft version: 1.18.1
litematica version: litematica-fabric-1.18.1-0.10.0
malilib version: malilib-fabric-1.18.1-0.11.4

issue: 
When I try to paste the schematic on the server, the client crash. The same schematic can be pasted properly when I am in the single player world. At first I thought it was because of too much pasted content, but I didn't know why the client crashed instead of the server

Here is a partial crash report

Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: Index -47 out of bounds for length 384
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
	at fi.dy.masa.litematica.scheduler.tasks.TaskPasteSchematicPerChunkCommand.generateStrips(TaskPasteSchematicPerChunkCommand.java:574)
	at fi.dy.masa.litematica.scheduler.tasks.TaskPasteSchematicPerChunkCommand.generateFillVolumes(TaskPasteSchematicPerChunkCommand.java:521)
	at fi.dy.masa.litematica.scheduler.tasks.TaskPasteSchematicPerChunkCommand.prepareSettingBlocks(TaskPasteSchematicPerChunkCommand.java:138)
	at fi.dy.masa.litematica.scheduler.tasks.TaskPasteSchematicPerChunkCommand.onStartNextBox(TaskPasteSchematicPerChunkCommand.java:126)
	at fi.dy.masa.litematica.scheduler.tasks.TaskProcessChunkMultiPhase.startNextBox(TaskProcessChunkMultiPhase.java:202)
	at fi.dy.masa.litematica.scheduler.tasks.TaskPasteSchematicPerChunkCommand.onNextChunkFetched(TaskPasteSchematicPerChunkCommand.java:118)
	at fi.dy.masa.litematica.scheduler.tasks.TaskProcessChunkMultiPhase.fetchNextChunk(TaskProcessChunkMultiPhase.java:181)
	at fi.dy.masa.litematica.scheduler.tasks.TaskProcessChunkMultiPhase.executeMultiPhase(TaskProcessChunkMultiPhase.java:97)
	at fi.dy.masa.litematica.scheduler.tasks.TaskPasteSchematicPerChunkCommand.execute(TaskPasteSchematicPerChunkCommand.java:101)
	at fi.dy.masa.litematica.scheduler.TaskScheduler.runTasks(TaskScheduler.java:65)
	at fi.dy.masa.litematica.scheduler.ClientTickHandler.onClientTick(ClientTickHandler.java:33)
	at fi.dy.masa.malilib.event.TickHandler.onClientTick(TickHandler.java:36)
	at net.minecraft.client.MinecraftClient.handler$ceo000$onPostKeyboardInput(MinecraftClient:17493)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1807)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1086)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by maruohon** [comment]
This was caused by a bug in the new fill-command-based pasting. It was also fixed a long time ago in version 0.10.1.

**Comment by monsters-97** [comment]
thanks for the bug fix.
