### ISSUE TITLE
Game crashing after loading a schematic

### ISSUE THREAD

**Issue by blugarek** [maruohon/litematica#546]
Yo, my game crashes every time i look at my schematic
Its big one, like 160x160x256 blocks but ye
Only mods im using are linematica and malilib, fabric 1.16.5
How can i avoid this?

Crash report (ik there are other mods but its report from another version, the same happens with only linematica and malilib):
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Skytils On Top (Skytils-1.2.6.temp.jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.7.0-beta.37064-for-MC-1.8.9.temp.jar)
  PatcherTweaker (Patcher-1.8.2 (1.8.9).temp.jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).temp.jar)
  ModTweaker (Patcher-1.8.2 (1.8.9).temp.jar)
  FeatherOpt (FeatherOpt-1.0.0-SNAPSHOT.temp.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 03.07.22 08:05
Description: Initializing game (unknown crash)

java.lang.NullPointerException: Initializing game (unknown crash)
	at net.digitalingot.feather.dj.tH(FeatherSourceFile:48)
	at net.digitalingot.feather.uv.onResourceManagerReload(FeatherSourceFile:10)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:120)
	at net.minecraft.client.Minecraft.handler$bmi000$wc(Minecraft.java:21594)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:529)
	at net.minecraft.client.Minecraft.run(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:126)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:72)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at cc.woverflow.onecore.tweaker.OneCoreTweaker.<init>(OneCoreTweaker.java:16)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.digitalingot.feather.dj.tH(FeatherSourceFile:48)
	at net.digitalingot.feather.uv.onResourceManagerReload(FeatherSourceFile:10)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:120)
	at net.minecraft.client.Minecraft.handler$bmi000$wc(Minecraft.java:21594)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:529)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:126)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:72)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at cc.woverflow.onecore.tweaker.OneCoreTweaker.<init>(OneCoreTweaker.java:16)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_332, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 3118688344 bytes (2974 MB) / 4261412864 bytes (4064 MB) up to 4261412864 bytes (4064 MB)
	JVM Flags: 9 total; -Xms4040M -Xmx4040M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ErrorFile=feather/java_error.log
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                          | Version        | Source                                                |
	| ----- | --------------------------- | -------------- | ----------------------------------------------------- |
	| U     | mcp                         | 9.19           | minecraft.jar                                         |
	| U     | FML                         | 8.0.99.99      | forge-1.8.9-11.15.1.2318-1.8.9-universal.jar          |
	| U     | Forge                       | 11.15.1.2318   | forge-1.8.9-11.15.1.2318-1.8.9-universal.jar          |
	| U     | essential                   | 1.0.0          | Essential (forge_1.8.9).jar                           |
	| U     | feather                     | 1.0.0-SNAPSHOT | feather-1.8.9-1.0.0-SNAPSHOT.jar                      |
	| U     | onecore                     | 1.3.4          | OneCore.jar                                           |
	| U     | sbp                         | 1.7.0.0        | 1.8.9.SkyblockPersonalized.1.7.0.0.temp.jar           |
	| U     | apec                        | 1.10.1         | Apec-1.10.1.temp.jar                                  |
	| U     | chatting                    | 1.4.1          | Chatting-1.4.1.temp.jar                               |
	| U     | cowlection                  | 1.8.9-0.14.0   | Cowlection-1.8.9-0.14.0.temp.jar                      |
	| U     | Danker's Skyblock Mod       | 1.8.7-beta6    | Dankers_Skyblock_Mod-1.8.7-beta6.1.temp.jar           |
	| U     | dungeonrooms                | 3.3.1          | Dungeon_Rooms-3.3.1.temp.jar                          |
	| U     | skyblock_dungeons_guide     | 1.0            | dungeonsguide-3.7.8.temp.jar                          |
	| U     | featheropt                  | 1.0.0-SNAPSHOT | FeatherOpt-1.0.0-SNAPSHOT.temp.jar                    |
	| U     | lunatriuscore               | 1.2.0.42       | LunatriusCore-1.12.2-1.2.0.42-universal.temp.jar      |
	| U     | notenoughupdates            | 2.1.0-REL      | NotEnoughUpdates-2.1-Wynncraft.temp.jar               |
	| U     | optibye                     | 1.0.0          | Optibye-1.0.0-dep.temp.jar                            |
	| U     | patcher                     | 1.8.2          | Patcher-1.8.2 (1.8.9).temp.jar                        |
	| U     | resourcepackmanager         | 1.2            | Resource_Pack_Manager_1.2.temp.jar                    |
	| U     | schematica                  | 1.8.0.169      | Schematica-1.12.2-1.8.0.169-universal.temp.jar        |
	| U     | text_overflow_scroll        | 1.4.0          | Scrollable Tooltips-1.4 (1.8.9).temp.jar              |
	| U     | simpletogglesprint          | 2.2.0          | SimpleToggleSprint-2.2.0.temp.jar                     |
	| U     | skyblockaddons              | 1.7.0-beta.3   | SkyblockAddons-1.7.0-beta.37064-for-MC-1.8.9.temp.jar |
	| U     | skyblockcatia               | 1.3.2          | SkyBlockcatia-1.8.9-1.3.2.temp.jar                    |
	| U     | skyblockclientupdater       | 1.2.6          | SkyblockClient-Updater-1.2.6.temp.jar                 |
	| U     | skyblockhud                 | 1.13           | SkyblockHud-1.13-beta7.temp.jar                       |
	| U     | skyclientcosmetics          | 1.1.9          | SkyClientCosmetics-1.1.9.temp.jar                     |
	| U     | skytils                     | 1.2.6          | Skytils-1.2.6.temp.jar                                |
	| U     | smooth-scrolling-everywhere | 1.2            | smooth-scrolling-everywhere-1.2.temp.jar              |

	Loaded coremods (and transformers): 
Skytils On Top (Skytils-1.2.6.temp.jar)
  skytils.skytilsmod.asm.SkytilsTransformer
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.7.0-beta.37064-for-MC-1.8.9.temp.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
PatcherTweaker (Patcher-1.8.2 (1.8.9).temp.jar)
  club.sk1er.patcher.tweaker.ClassTransformer
FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).temp.jar)
  club.sk1er.mods.scrollabletooltips.forge.ClassTransformer
ModTweaker (Patcher-1.8.2 (1.8.9).temp.jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
FeatherOpt (FeatherOpt-1.0.0-SNAPSHOT.temp.jar)
  net.digitalingot.featheropt.FeatherOptAccessTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.75' Renderer: 'GeForce MX150/PCIe/SSE2'
	Skytils Debug Info: {HasBetterFPS=false, BetterFPS Version=NONE, Disabled Start Checks=false}
	Launched Version: 1.8.9-feather
	LWJGL: 2.9.4
	OpenGL: GeForce MX150/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.75, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'Feather Forge'
	Type: Client (map_client.txt)
	Resource Packs: ! §4WAR 16x §7[REVAMP]AXN.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.75
	OpenGlRenderer: GeForce MX150/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by maruohon** [comment]
That log is completely useless to me. It doesn't even have malilib and Litematica installed. How am I supposed to know why/how it crashes with Litematica if you send some other random crash log?

**Comment by maruohon** [comment]
That log is even from 1.12.2...

**Comment by alex-huff** [comment]
The logs you sent are from a client with Lunatrius' Schematica mod. litematica is a completely different mod from Schematica. In your client, Schematica is installed for the 1.12.2 version of the game. The crash log you sent is from a 1.8.9 instance of that client, which appears to be Feather Client. You are asking for help with 1.16.5 litematica/malilib. Even if a crash log from a different version of litematica could help in your case (unlikely), your client does not have litematica, it has Schematica, and the current profile is not even set to the same Minecraft version that your Schematica is installed in. If you are serious about solving this issue, I would recommend first getting the correct logs, and describing what action actually causes the crash.
