### ISSUE TITLE
Crash de mon minrcraft

### ISSUE THREAD

**Issue by Ex0ss** [maruohon/litematica#549]
Yo ! Je n'ai jamais eu de problème avec litematica mais depuis le passage en 1.19.1 avec la nouvelle version de litematica, mon jeu crash lorsque je veux changer la manière de voir mon schématique, je m'explique : quand je veux voir le schéma couche après couche donc (par exemple) si je suis a la couche Y=70 et que je veux passer à la couche Y=71 mon jeu crash. Je précise que j'ai la bonne version de litematica ainsi que malilib installé. Merci  pour vos réponses.

**Comment by maruohon** [comment]
Are you changing the render layer while you are not logged in to the world? That is known to crash in the current version. Otherwise please post the crash log.

**Comment by Ex0ss** [comment]
Non je ne crois pas avoir changer la couche de rendu lorsque je ne suis pas connecté au monde voici le rapport :



---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2022-08-02 22:40:45
Description: Unexpected error

java.lang.NoSuchFieldError: field_11733
	at fi.dy.masa.malilib.util.InfoUtils.printActionbarMessage(InfoUtils.java:146)
	at fi.dy.masa.malilib.util.LayerRange.moveLayer(LayerRange.java:369)
	at fi.dy.masa.litematica.event.KeyCallbacks$KeyCallbackHotkeys.onKeyAction(KeyCallbacks.java:404)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:185)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:145)
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:270)
	at fi.dy.masa.malilib.event.InputEventHandler.onKeyInput(InputEventHandler.java:143)
	at net.minecraft.class_309.handler$bgi000$onKeyboardInput(class_309.java:1083)
	at net.minecraft.class_309.method_1466(class_309.java:316)
	at net.minecraft.class_309.method_22678(class_309.java:462)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_309.method_22676(class_309.java:462)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1207)
	at net.minecraft.class_310.method_1514(class_310.java:767)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fi.dy.masa.malilib.util.InfoUtils.printActionbarMessage(InfoUtils.java:146)
	at fi.dy.masa.malilib.util.LayerRange.moveLayer(LayerRange.java:369)
	at fi.dy.masa.litematica.event.KeyCallbacks$KeyCallbackHotkeys.onKeyAction(KeyCallbacks.java:404)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:185)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:145)
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:270)
	at fi.dy.masa.malilib.event.InputEventHandler.onKeyInput(InputEventHandler.java:143)
	at net.minecraft.class_309.handler$bgi000$onKeyboardInput(class_309.java:1083)
	at net.minecraft.class_309.method_1466(class_309.java:316)
	at net.minecraft.class_309.method_22678(class_309.java:462)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_309.method_22676(class_309.java:462)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Affected level --
Details:
	All players: 1 total; [class_746['Ex0ss_'/99, l='ClientLevel', x=-128.10, y=-4.70, z=-21.43]]
	Chunk stats: 1024, 615
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-8,0), Section: (at 0,8,0 in 0,-1,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 337785 game time, 169094 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2338)
	at net.minecraft.class_310.method_1514(class_310.java:791)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.1
	Minecraft Version ID: 1.19.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 717872312 bytes (684 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 960M
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x139b
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1215
	Graphics card #1 name: Intel(R) HD Graphics 530
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x191b
	Graphics card #1 versionInfo: DriverVersion=27.20.100.7990
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 14502.61
	Virtual memory used (MB): 10214.81
	Swap memory total (MB): 6400.00
	Swap memory used (MB): 253.91
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.58.5+1.19.1
			fabric-api-base: Fabric API Base 0.4.9+e62f51a395
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f4095
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.15+d5533c0195
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f4095
			fabric-command-api-v1: Fabric Command API (v1) 1.2.9+f71b366f95
			fabric-command-api-v2: Fabric Command API (v2) 2.1.5+0c17ea9695
			fabric-commands-v0: Fabric Commands (v0) 0.2.26+df3654b395
			fabric-containers-v0: Fabric Containers (v0) 0.1.31+df3654b395
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213e95
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d2495
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4a95
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.5+a680b9b495
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f78595
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f4095
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f4095
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b395
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+1899036195
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c4395
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f4095
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f4095
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b395
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc73895
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e56895
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c695
			fabric-message-api-v1: Fabric Message API (v1) 5.0.1+4e0178f495
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc73895
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f4095
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.1+3082331495
			fabric-networking-v0: Fabric Networking (v0) 0.3.18+df3654b395
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f4095
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553a95
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.21+23c4cfef95
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f4095
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39f95
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b395
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f4095
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f4095
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b395
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f4095
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a395
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e095
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effaf95
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.10+9ff28f4095
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f4095
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a395
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c695
		fabricloader: Fabric Loader 0.14.8
		iris: Iris 1.2.6
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		litematica: Litematica 0.12.3
		lithium: Lithium 0.8.3
		malilib: MaLiLib 0.13.0
		minecraft: Minecraft 1.19.1
		phosphor: Phosphor 0.8.1
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		xaerominimap: Xaero's Minimap 22.13.0
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.8-1.19.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 960M/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.15, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (United Kingdom)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Ex0ss_'/99, l='ServerLevel[Redstone]', x=-128.10, y=-4.70, z=-21.43]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable

**Comment by maruohon** [comment]
I assume this was caused by using malilib for the wrong MC version?
