### ISSUE TITLE
Error: zip END header not found

### ISSUE THREAD

**Issue by grillgamesh** [maruohon/litematica#571]
MC JARFILE Version: 1.18.2, Fabric v.0.14.9
Mod JARFILE: Litematica-fabric-1.18.2-.0.11.3.jar (taken from [here](https://www.curseforge.com/minecraft/mc-mods/litematica/files/3783909)

mallib version 0.12.1 (taken from curseforge's page as well)

error message from fabric API's loader:

```Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:146)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:146)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:210)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [C:\Users\ADMIN\AppData\Roaming\gdlauncher_next\instances\Fabulously Optimized\mods\litematica-fabric-1.18.2-0.11.3.jar]: java.util.zip.ZipException: zip END header not found
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.get(Unknown Source)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:143)
	... 5 more
Caused by: java.lang.RuntimeException: Error analyzing [C:\Users\ADMIN\AppData\Roaming\gdlauncher_next\instances\Fabulously Optimized\mods\litematica-fabric-1.18.2-0.11.3.jar]: java.util.zip.ZipException: zip END header not found
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:263)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:212)
	at java.base/java.util.concurrent.RecursiveTask.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.initCEN(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:284)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:253)
	... 7 more
```

![image](https://user-images.githubusercontent.com/98428877/187000238-c556fde9-283d-48ad-bab0-d1e59573fc8a.png)

DxDiag is also attached, in case it's something to do with my specific system's incompatibilities..... 🤷
[DxDiag.txt](https://github.com/maruohon/litematica/files/9436752/DxDiag.txt)

Contact me via github, or discord at `@Gilgamesh#0028`, if any additional information is required.

**Comment by maruohon** [comment]
Your mod file is either incomplete or corrupted. Try re-downloading it, and also check the file size. Maybe it's currently 0 bytes?

**Comment by grillgamesh** [comment]
How big should the jarfile be? 
Mine shows as 113KB.

Regardless, a redownload fixed it.
Perhaps a packet simply didnt make it.
Darn you, UDP! :dogekek:
