### ISSUE TITLE
Litematica 1.19 crashing after loading the world

### ISSUE THREAD

**Issue by Britanniann** [maruohon/litematica#576]
The title explains it all, I'm not using 1.19.1/1.19.2, here is the crash report:

https://pastebin.pl/view/930ab7dc

**Comment by maruohon** [comment]
Ah great, another one of those mysterious AMD driver crashes. (Basically the same as  #558, #559, #562)

Currently I have no idea why this happens...

**Comment by maruohon** [comment]
Okay I did some testing on my old PC that still has Windows 10 installed on it. I too do get the crash with the latest 22.8.2 AMD graphics drivers, if I use a larger render distance. Something around rd 20 or larger starts to be unstable, ~24 or higher crashes almost instantly after logging in to a world, at least if trying to open the F3 screen (wtf). But installing the 22.5.1 WHQL version of the AMD drivers and the crashes are gone.

So try changing your AMD graphics driver version to 22.5.1 (WHQL).

**Comment by Britanniann** [comment]
Decreased my render distance to 16 and now the game doesn't crash, hadn't yet tested the older AMD graphics card version. Thanks for helping!

**Comment by nepp95** [comment]
I also have the same problem. AMD driver 22.7.1 introduced massive openGL improvements, but with massive improvements, I’m sure bugs will have slipped their way through as well. To be even more sure: it crashes on my desktop with amd. It works fine on my laptop (exact same game folder) with an nvidia card.

Workaround at the moment: lower render distance or revert driver updates, the latter nog being recommended.

This should be reported to AMD.

**Comment by kosma** [comment]
According to masa: 
> so apparently 22.7.1 broke it
> I just tested with 22.8.2 (broken) and 22.5.1 (working)

**Comment by fujimite** [comment]
I have the same issue, it's also fixed by lowering the render distance to 16. I can increase render distance once in game without crashing, but the chunks glitch out and dissapear. But no crash. Opening F3 screen doesnt crash me either. Driver version 22.9.2, minecraft 1.19.2

**Comment by ZenSkylark** [comment]
#622 is it related?

**Comment by nepp95** [comment]
> #622 is it related?

Both driver related but different issues I think.

**Comment by Aaroneisele55** [comment]
I also have crashes when I join a server, I am on 1.21.5, here are my logs:

```
---- Minecraft Crash Report ----
// My bad.

Time: 2025-05-10 15:39:34
Description: Ticking entity

java.lang.IllegalArgumentException: Invalid selected slot
	at knot//net.minecraft.class_1661.method_61496(class_1661.java:63)
	at knot//me.aleksilassila.litematica.printer.actions.PrepareAction.addPickBlock(PrepareAction.java:99)
	at knot//me.aleksilassila.litematica.printer.actions.PrepareAction.send(PrepareAction.java:63)
	at knot//me.aleksilassila.litematica.printer.ActionHandler.onGameTick(ActionHandler.java:38)
	at knot//net.minecraft.class_746.handler$bmg002$litematica_printer$tick(class_746.java:1940)
	at knot//net.minecraft.class_746.method_5773(class_746.java:248)
	at knot//net.minecraft.class_638.method_18646(class_638.java:288)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:510)
	at knot//net.minecraft.class_638.method_32124(class_638.java:267)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_638.method_18116(class_638.java:263)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1890)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1314)
	at knot//net.minecraft.class_310.method_1514(class_310.java:936)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_1661.method_61496(class_1661.java:63)
	at knot//me.aleksilassila.litematica.printer.actions.PrepareAction.addPickBlock(PrepareAction.java:99)
	at knot//me.aleksilassila.litematica.printer.actions.PrepareAction.send(PrepareAction.java:63)
	at knot//me.aleksilassila.litematica.printer.ActionHandler.onGameTick(ActionHandler.java:38)
	at knot//net.minecraft.class_746.handler$bmg002$litematica_printer$tick(class_746.java:1940)
	at knot//net.minecraft.class_746.method_5773(class_746.java:248)
	at knot//net.minecraft.class_638.method_18646(class_638.java:288)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:510)
	at knot//net.minecraft.class_638.method_32124(class_638.java:267)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_638.method_18116(class_638.java:263)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 1939
	Entity Name: {MINECRAFT_USERNAME}
	Entity's Exact location: 66.14, 71.00, 132.56
	Entity's Block location: World: (66,71,132), Section: (at 2,7,4 in 4,4,8; chunk contains blocks 64,-64,128 to 79,319,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.03, -0.08, -0.10
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:510)
	at knot//net.minecraft.class_638.method_32124(class_638.java:267)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_638.method_18116(class_638.java:263)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1890)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1314)
	at knot//net.minecraft.class_310.method_1514(class_310.java:936)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 40.297s
	Wall uptime: 28.428s
	High-res time: 23.418s
	Client ticks: 257 ticks / 12.850s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2382)
	at knot//net.minecraft.class_310.method_54580(class_310.java:1005)
	at knot//net.minecraft.class_310.method_1514(class_310.java:957)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; class_746{name={MINECRAFT_USERNAME}, id=1939, pos=(66.14300975994016, 71.0, 132.56137684355602), mode=CREATIVE, permission=4}
	Chunk stats: 1089, 512
	Level dimension: minecraft:overworld
	Level spawn location: World: (12,72,-149), Section: (at 12,8,11 in 0,4,-10; chunk contains blocks 0,-64,-160 to 15,319,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 5126481 game time, 12000 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
	Tracked entity count: 125

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, accessible-step, appleskin, axiom, cloth-config, continuity, distanthorizons, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-tag-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, jade, litematica, litematica_printer, malilib, meteor-client, skinshuffle, sodium, spruceui, voidcommands, xaerominimap, xaeroworldmap, yet_another_config_lib_v3, file/ultimacraft-pbr-v-1-9.zip, file/LowOnFire 1.21.5.zip, continuity:default, continuity:glass_pane_culling_fix

-- System Details --
Details:
	Minecraft Version: 1.21.5
	Minecraft Version ID: 1.21.5
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 23.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 208249872 bytes (198 MiB) / 1140850688 bytes (1088 MiB) up to 31474057216 bytes (30016 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 4060
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 8188.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6094
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MiB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MiB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MiB): 34730.11
	Virtual memory used (MiB): 17035.87
	Swap memory total (MiB): 2048.00
	Swap memory used (MiB): 6.19
	Space in storage for jna.tmpdir (MiB): available: 37432.49, total: 952453.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 37432.49, total: 952453.00
	Space in storage for io.netty.native.workdir (MiB): available: 37432.49, total: 952453.00
	Space in storage for java.io.tmpdir (MiB): available: 37432.49, total: 952453.00
	Space in storage for workdir (MiB): available: 37432.49, total: 952453.00
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx30016M
	Fabric Mods: 
		accessible-step: Accessible Step 2.1.0+1.21.2
			blue_endless_jankson: jankson 1.2.3
		appleskin: AppleSkin 3.0.6+mc1.21.5
			cloth-config: Cloth Config v17 18.0.145
				cloth-basic-math: cloth-basic-math 0.6.1
		axiom: Axiom 4.8.0
			com_moulberry_axiomclientapi: axiomclientapi 1.0.0
			com_moulberry_mixinconstraints: mixinconstraints 1.0.8
		continuity: Continuity 3.0.1-test.4+1.21.5
		distanthorizons: Distant Horizons 2.3.2-b
			fabric-api-base: Fabric API Base 0.4.62+73a52b4b07
			fabric-command-api-v2: Fabric Command API (v2) 2.2.49+73a52b4b07
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.25+27c1078f07
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 4.0.13+73a52b4b07
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.63+ecf51cdc07
			fabric-networking-api-v1: Fabric Networking API (v1) 4.4.0+f3ffa98907
			fabric-rendering-v1: Fabric Rendering (v1) 11.1.11+081cc04307
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.46+86c3a9f107
		fabric-api: Fabric API 0.123.2+1.21.5
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.96+86c3a9f149
			fabric-biome-api-v1: Fabric Biome API (v1) 16.0.7+2dd063df49
			fabric-block-api-v1: Fabric Block API (v1) 1.0.37+86c3a9f149
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.26+aa6d566c49
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.16+86c3a9f149
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.37+86c3a9f149
			fabric-command-api-v1: Fabric Command API (v1) 1.2.70+f71b366f49
			fabric-commands-v0: Fabric Commands (v0) 0.2.87+df3654b349
			fabric-content-registries-v0: Fabric Content Registries (v0) 10.0.14+3e6c1f7d49
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.30+7f945d5b49
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.14.4+fca633a049
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.12+86c3a9f149
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.8.1+7d6345b349
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 22.3.6+fd2b524049
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.17+3e6c1f7d49
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.70+c327076a49
			fabric-item-api-v1: Fabric Item API (v1) 11.4.1+e46fd76a49
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.2.9+3459fc6149
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.61+df3654b349
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.6.0+230071a049
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.48+3f89f5a549
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.36+86c3a9f149
			fabric-message-api-v1: Fabric Message API (v1) 6.0.33+86c3a9f149
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 5.2.0+c982b95149
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 21.1.0+b8d6ba7049
			fabric-particles-v1: Fabric Particles (v1) 4.1.1+112e550e49
			fabric-recipe-api-v1: Fabric Recipe API (v1) 8.1.6+052a85d049
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 6.1.20+b556383249
			fabric-renderer-api-v1: Fabric Renderer API (v1) 6.0.2+c982b95149
			fabric-renderer-indigo: Fabric Renderer - Indigo 3.0.3+3e6c1f7d49
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.64+73761d2e49
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.27+86c3a9f149
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.21+73a52b4b49
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.1.7+847e5f5c49
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.127+c327076a49
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.38+86c3a9f149
			fabric-tag-api-v1: Fabric Tag API (v1) 1.0.17+ecf51cdc49
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.24+7b20cbb049
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.3.17+f17a180c49
		fabricloader: Fabric Loader 0.16.14
			mixinextras: MixinExtras 0.4.1
		iris: Iris 1.8.11+mc1.21.5
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		jade: Jade 18.2.0+fabric
		java: Java HotSpot(TM) 64-Bit Server VM 23
		litematica: Litematica 0.22.1
		litematica_printer: Litematica Printer 3.2.1-sakura.5
		malilib: MaLiLib 0.24.1
		meteor-client: Meteor Client 1.21.5-16
		minecraft: Minecraft 1.21.5
		mousetweaks: Mouse Tweaks 2.27
		skinshuffle: SkinShuffle 2.9.1+1.21.5
			com_drewnoakes_metadata-extractor: metadata-extractor 2.19.0
			com_konghq_unirest-java_standalone: unirest-java 3.11.9
			commons-validator_commons-validator: commons-validator 1.7
			org_jsoup_jsoup: jsoup 1.16.1
			spruceui: SpruceUI 7.0.0+1.21.5
			yet_another_config_lib_v3: YetAnotherConfigLib 3.6.6+1.21.5-fabric
				com_twelvemonkeys_common_common-image: common-image 3.12.0
				com_twelvemonkeys_common_common-io: common-io 3.12.0
				com_twelvemonkeys_common_common-lang: common-lang 3.12.0
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.12.0
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.12.0
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.12.0
				org_quiltmc_parsers_gson: gson 0.2.1
				org_quiltmc_parsers_json: json 0.2.1
		sodium: Sodium 0.6.13+mc1.21.5
		voidcommands: Void Commands 1.5+1.21.5
			clientarguments: clientarguments 1.11.1
		xaerominimap: Xaero's Minimap 25.2.6
		xaeroworldmap: Xaero's World Map 1.39.8
	Loaded Shaderpack: (off)
	Launched Version: 1.21.5
	Launcher name: theseus
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 4060/PCIe/SSE2 GL version 3.2.0 NVIDIA 560.94, NVIDIA Corporation
	Window size: 2560x1440
	GFLW Platform: win32
	Render Extensions: GL_KHR_debug, GL_ARB_vertex_attrib_binding, GL_ARB_direct_state_access
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, accessible-step, appleskin (incompatible), axiom, cloth-config, continuity, distanthorizons, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-tag-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, jade (incompatible), litematica, litematica_printer, malilib, meteor-client, skinshuffle, sodium, spruceui, voidcommands, xaerominimap (incompatible), xaeroworldmap (incompatible), yet_another_config_lib_v3 (incompatible), file/ultimacraft-pbr-v-1-9.zip (incompatible), file/LowOnFire 1.21.5.zip, continuity:default, continuity:glass_pane_culling_fix
	Current Language: en_us
	Locale: de_DE
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 

-- Meteor Client --

Version: 1.21.5
Build: 16

[[ Active Modules ]]

[Combat]:
auto-totem
auto-weapon
hitboxes
hole-filler

[Player]:
anti-hunger
multitask
reach
speed-mine

[Movement]:
elytra-boost
no-fall

[Render]:
esp
fullbright
```
