### ISSUE TITLE
Сrash game in area select

### ISSUE THREAD

**Issue by AimVFullAhue** [maruohon/litematica#579]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2022-09-08 15:35:27
Description: Unexpected error

java.lang.NoSuchFieldError: field_11733
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at fi.dy.masa.malilib.util.InfoUtils.printActionbarMessage(InfoUtils.java:146)
	at fi.dy.masa.litematica.selection.SelectionManager.setPositionOfCurrentSelectionToRayTrace(SelectionManager.java:559)
	at fi.dy.masa.litematica.event.KeyCallbacks$KeyCallbackHotkeys.onKeyAction(KeyCallbacks.java:218)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:185)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:145)
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:270)
	at fi.dy.masa.malilib.event.InputEventHandler.onMouseClick(InputEventHandler.java:172)
	at net.minecraft.client.Mouse.handler$zld000$hookOnMouseClick(Mouse:1056)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:54)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:118)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:198)
	at net.minecraft.client.util.Window.swapBuffers(Window:453)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1205)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at net.minecraft.client.main.Main.method_44604(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fi.dy.masa.malilib.util.InfoUtils.printActionbarMessage(InfoUtils.java:146)
	at fi.dy.masa.litematica.selection.SelectionManager.setPositionOfCurrentSelectionToRayTrace(SelectionManager.java:559)
	at fi.dy.masa.litematica.event.KeyCallbacks$KeyCallbackHotkeys.onKeyAction(KeyCallbacks.java:218)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:185)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:145)
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:270)
	at fi.dy.masa.malilib.event.InputEventHandler.onMouseClick(InputEventHandler.java:172)
	at net.minecraft.class_312.handler$zld000$hookOnMouseClick(class_312.java:1056)
	at net.minecraft.class_312.method_1601(class_312.java:54)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:198)

-- Affected level --
Details:
	All players: 3 total; [class_746['Mucop'/652077, l='ClientLevel', x=12.68, y=63.00, z=5.13], class_745['Munular'/494177, l='ClientLevel', x=17.01, y=72.50, z=18.30], class_745['qirieshka_clwn'/617920, l='ClientLevel', x=24.58, y=77.50, z=21.58]]
	Chunk stats: 961, 461
	Level dimension: minecraft:overworld
	Level spawn location: World: (32,70,48), Section: (at 0,6,0 in 2,4,3; chunk contains blocks 32,-64,48 to 47,319,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 113082 game time, 86589073 day time
	Server brand: Matter (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:580)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Anti_fire_16x_1.11_1.12.2_.zip, Better-Leaves-7.1-1.19+.zip, Icons+V.1.7.1.zip, IslanasArmorAccessories1-19Full.zip, KSEPSP+v8+1+cut.zip, Plasmo_Pack_1.1.0.zip, xali-s-Enchanted-Books-16x-v0.10.1.zip, BushyBiomesV1.12.zip, Improved+Moss+-+1.19.zip, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 886402744 bytes (845 MiB) / 3590324224 bytes (3424 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f11
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 21679.24
	Virtual memory used (MB): 14972.14
	Swap memory total (MB): 5376.00
	Swap memory used (MB): 1103.41
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.60.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.11+e62f51a390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.9+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.17+aeb40ebe90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.20+aeb40ebe90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.1+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.11+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.7+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.28+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.34+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.3+aeb40ebe90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.1+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.5+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.8+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.30+aeb40ebe90
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.18+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.28+aeb40ebe90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.28+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.21+aeb40ebe90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.7+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.28+aeb40ebe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.20+aeb40ebe90
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.18+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.2+aeb40ebe90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.3+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.6+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.3+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.14+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.17+aeb40ebe90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.4+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.21+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.11+aeb40ebe90
			fabric-particles-v1: Fabric Particles (v1) 1.0.10+aeb40ebe90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.24+aeb40ebe90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.10+aeb40ebe90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.12+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.20+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.14+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.7+aeb40ebe90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.22+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.16+aeb40ebe90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.11+e62f51a390
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.1+aeb40ebe90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.26+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.13+9ff28f4090
			fabric-textures-v0: Fabric Textures (v0) 1.0.20+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.11+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.0+42d99c3290
		fabricloader: Fabric Loader 0.14.9
		fallingleaves: Falling Leaves 1.12.0+1.19
		gammautils: Gamma Utils 1.6.10
		horsestatsvanilla: Horse Stats Vanilla 4.2.1
			cloth-config: Cloth Config v6 7.0.72
				cloth-basic-math: cloth-basic-math 0.6.1
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		java: OpenJDK 64-Bit Server VM 17
		languagereload: Language Reload 1.2.4
		litematica: Litematica 0.12.4
		malilib: MaLiLib 0.13.0
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.0.5
		nochatreports: No Chat Reports 1.19.2-v1.10.1
		notenoughcrashes: Not Enough Crashes 4.1.8+1.19.2
		optifabric: OptiFabric 1.13.16
			mm: Manningham Mills 2.3
		plasmo_voice: Plasmo Voice 1.2.19
		replaymod: Replay Mod 1.19.1-2.6.8
		shulkerboxtooltip: Shulker Box Tooltip 3.0.9-beta.1+1.19-rc2
		viafabric: ViaFabric 0.4.8+12-main
			org_yaml_snakeyaml: snakeyaml 1.30
			viafabric-mc119: ViaFabric for 1.19 0.4.8+12-main
			viaversion: ViaVersion 4.4.0
		visuality: Visuality 0.5.0
	Launched Version: fabric-loader-0.14.9-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.94, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/Anti_fire_16x_1.11_1.12.2_.zip (incompatible), file/Better-Leaves-7.1-1.19+.zip, file/Icons+V.1.7.1.zip, file/IslanasArmorAccessories1-19Full.zip, file/KSEPSP+v8+1+cut.zip (incompatible), file/Plasmo_Pack_1.1.0.zip (incompatible), file/xali-s-Enchanted-Books-16x-v0.10.1.zip, file/BushyBiomesV1.12.zip, file/Improved+Moss+-+1.19.zip
	Current Language: Русский (Россия)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	OptiFine Version: OptiFine_1.19.2_HD_U_H9
	OptiFine Build: 20220820-230904
	Render Distance Chunks: 13
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 516.94
	OpenGlRenderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Litematica (litematica), MaLiLib (malilib)

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.19.2
	OptiFine jar version: OptiFine_1.19.2_HD_U_H9
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/iaim4/AppData/Roaming/.minecraft/.optifine/OptiFine_1.19.2_HD_U_H9/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by maruohon** [comment]
I'm assuming your malilib is for 1.19.0 and not for 1.19.2?
