### ISSUE TITLE
Error with carpet extra

### ISSUE THREAD

**Issue by mbido** [maruohon/litematica#610]
Hello, my problem is that I want to use tweakeroo's flexible and accurate placement on my fabric server (1.19.2) but every time I try to install carpet-extrat with fabric-carpet, my server won't start.
```
[20:30:19] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71) ~[fabric-loader-0.14.9.jar:?]
Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod dimthread
at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.9.jar:?]
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: Namespace (named) does not match current runtime namespace (intermediary)
at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285) ~[access-widener-2.1.0.jar:?]
at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84) ~[access-widener-2.1.0.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.9.jar:?]
```

**Comment by vacla** [comment]
@mbido can you sent the full crashlog?

**Comment by mbido** [comment]
This is every thing the server sent to me :
```
openjdk version "17.0.4.1" 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)
STARTUP /home/container: java -Xms128M -Xmx6827M -Dterminal.jline=false -Dterminal.ansi=true -Djline.terminal=jline.UnsupportedTerminal -jar ${SERVER_JARFILE}
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[20:38:33] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
[20:38:33] [ForkJoinPool-1-worker-3/WARN]: Mod dimthread uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[20:38:33] [ForkJoinPool-1-worker-8/WARN]: The mod "passivepregen" contains invalid entries in its mod json:
- Unsupported root entry "__comment" at line 15 column 16
- Unsupported root entry "access_widener" at line 16 column 21
[20:38:33] [main/INFO]: Loading 63 mods:
- carpet 1.4.84
- carpet-fixes 1.19-1.12.2
- carpet-tis-addition 1.41.1
- com_github_llamalad7_mixinextras 0.0.6 via carpet-fixes
- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
- conditional-mixin 0.3.1 via carpet-fixes
- connectivity 1.19-3.3
- dimthread ${version}
- fabric-api 0.62.0+1.19.2
- fabric-api-base 0.4.12+93d8cb8290 via fabric-api
- fabric-api-lookup-api-v1 1.6.10+93d8cb8290 via fabric-api
- fabric-biome-api-v1 9.0.18+c6af733c90 via fabric-api
- fabric-command-api-v1 1.2.12+f71b366f90 via fabric-api
- fabric-command-api-v2 2.1.8+93d8cb8290 via fabric-api
- fabric-commands-v0 0.2.29+df3654b390 via fabric-api
- fabric-containers-v0 0.1.35+df3654b390 via fabric-api
- fabric-content-registries-v0 3.3.1+624e468e90 via fabric-api
- fabric-convention-tags-v1 1.1.2+93d8cb8290 via fabric-api
- fabric-crash-report-info-v1 0.2.6+aeb40ebe90 via fabric-api
- fabric-data-generation-api-v1 5.2.0+b598f4ac90 via fabric-api
- fabric-dimensions-v1 2.1.32+0dd10df690 via fabric-api
- fabric-entity-events-v1 1.4.19+9ff28f4090 via fabric-api
- fabric-events-interaction-v0 0.4.29+c6af733c90 via fabric-api
- fabric-events-lifecycle-v0 0.2.29+df3654b390 via fabric-api
- fabric-game-rule-api-v1 1.0.22+c6af733c90 via fabric-api
- fabric-item-api-v1 1.5.8+93d8cb8290 via fabric-api
- fabric-item-groups-v0 0.3.30+93d8cb8290 via fabric-api
- fabric-language-kotlin 1.8.5+kotlin.1.7.20
- fabric-lifecycle-events-v1 2.2.0+33ffe9ec90 via fabric-api
- fabric-loot-api-v2 1.1.4+83a8659290 via fabric-api
- fabric-loot-tables-v1 1.1.7+9e7660c690 via fabric-api
- fabric-message-api-v1 5.0.4+93d8cb8290 via fabric-api
- fabric-mining-level-api-v1 2.1.15+33fbc73890 via fabric-api
- fabric-networking-api-v1 1.2.5+c6af733c90 via fabric-api
- fabric-networking-v0 0.3.22+df3654b390 via fabric-api
- fabric-object-builder-api-v1 4.0.12+93d8cb8290 via fabric-api
- fabric-particles-v1 1.0.11+79adfe0a90 via fabric-api
- fabric-registry-sync-v0 0.9.26+c6af733c90 via fabric-api
- fabric-rendering-data-attachment-v1 0.3.15+aeb40ebe90 via fabric-api
- fabric-rendering-fluids-v1 3.0.8+c6af733c90 via fabric-api
- fabric-resource-conditions-api-v1 2.0.12+a29562c890 via fabric-api
- fabric-resource-loader-v0 0.7.0+93d8cb8290 via fabric-api
- fabric-screen-handler-api-v1 1.3.1+1cc24b1b90 via fabric-api
- fabric-transfer-api-v1 2.1.1+93d8cb8290 via fabric-api
- fabric-transitive-access-wideners-v1 1.3.1+42d99c3290 via fabric-api
- fabricloader 0.14.9
- java 17
- krypton 0.2.1
- minecraft 1.19.2
- org_jetbrains_kotlin_kotlin-reflect 1.7.20 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib 1.7.20 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.20 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.20 via fabric-language-kotlin
- org_jetbrains_kotlinx_atomicfu-jvm 0.18.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
- org_yaml_snakeyaml 1.30 via carpet-tis-addition
- passivepregen 1.0.3
- starlight 1.1.1+fabric.ae22326
[20:38:33] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71) ~[fabric-loader-0.14.9.jar:?]
Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod dimthread
at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.9.jar:?]
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: Namespace (named) does not match current runtime namespace (intermediary)
at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285) ~[access-widener-2.1.0.jar:?]
at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84) ~[access-widener-2.1.0.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.9.jar:?]
```

**Comment by vacla** [comment]
This seems to be caused by the mod "dimthread"

**Comment by mbido** [comment]
Oh, right it seems better now thanks a lot for your responsiveness !

**Comment by maruohon** [comment]
This isn't even in any way related to Litematica.
