### ISSUE TITLE
Schematic loading error (crash)

### ISSUE THREAD

**Issue by SolracPq** [maruohon/litematica#636]
Error when opening a schematic, Minecraft is closed when wanting to generate it, generated and open the month of December.  I think it's because of the Create Mod (Fabric, version 0.5.0g, 1.19.2) Litematica (Fabric, version 0.12.5, 1.19.2) Malilib (Fabric, versión 0.13.0, 1.19.2), schematic created with full items from the Create Mod. Help please, I am creating an Iron and Gold farm on a Server (It does not have more mods that modify the world) it also doesn't work in SinglePlayer or Multiplayer world in both Crashea.

**Comment by rycbar0** [comment]
do you have a crashlog

**Comment by SolracPq** [comment]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2022-12-27 02:43:04
Description: mouseClicked event handler

java.lang.RuntimeException: this should be overridden via mixin. what?
	at io.github.fabricators_of_create.porting_lib.extensions.transfer.LevelExtensions.port_lib$getItemCache(LevelExtensions.java:12)
	at io.github.fabricators_of_create.porting_lib.transfer.TransferUtil.getItemCache(TransferUtil.java:666)
	at com.simibubi.create.content.logistics.block.chute.ChuteTileEntity.method_31662(ChuteTileEntity.java:106)
	at net.minecraft.class_2818.method_12007(class_2818.java:366)
	at fi.dy.masa.litematica.world.ChunkSchematic.method_12010(ChunkSchematic.java:123)
	at fi.dy.masa.litematica.world.WorldSchematic.method_8652(WorldSchematic.java:136)
	at fi.dy.masa.litematica.materials.MaterialCache.getItemForStateFromWorld(MaterialCache.java:95)
	at fi.dy.masa.litematica.materials.MaterialCache.getRequiredBuildItemForState(MaterialCache.java:71)
	at fi.dy.masa.litematica.materials.MaterialCache.getRequiredBuildItemForState(MaterialCache.java:62)
	at fi.dy.masa.litematica.materials.MaterialListUtils.convertStatesToStacks(MaterialListUtils.java:110)
	at fi.dy.masa.litematica.materials.MaterialListUtils.getMaterialList(MaterialListUtils.java:73)
	at fi.dy.masa.litematica.materials.MaterialListUtils.createMaterialListFor(MaterialListUtils.java:55)
	at fi.dy.masa.litematica.materials.MaterialListSchematic.reCreateMaterialList(MaterialListSchematic.java:34)
	at fi.dy.masa.litematica.materials.MaterialListSchematic.<init>(MaterialListSchematic.java:27)
	at fi.dy.masa.litematica.materials.MaterialListSchematic.<init>(MaterialListSchematic.java:15)
	at fi.dy.masa.litematica.gui.GuiSchematicLoad$ButtonListener.actionPerformedWithButton(GuiSchematicLoad.java:204)
	at fi.dy.masa.malilib.gui.button.ButtonBase.onMouseClickedImpl(ButtonBase.java:81)
	at fi.dy.masa.malilib.gui.widgets.WidgetBase.onMouseClicked(WidgetBase.java:92)
	at fi.dy.masa.malilib.gui.GuiBase.onMouseClicked(GuiBase.java:270)
	at fi.dy.masa.malilib.gui.GuiListBase.onMouseClicked(GuiListBase.java:92)
	at fi.dy.masa.malilib.gui.GuiBase.method_25402(GuiBase.java:212)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:204)
	at net.minecraft.class_1041.method_15998(class_1041.java:315)
	at net.minecraft.class_310.method_1523(class_310.java:1205)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.fabricators_of_create.porting_lib.extensions.transfer.LevelExtensions.port_lib$getItemCache(LevelExtensions.java:12)
	at io.github.fabricators_of_create.porting_lib.transfer.TransferUtil.getItemCache(TransferUtil.java:666)
	at com.simibubi.create.content.logistics.block.chute.ChuteTileEntity.method_31662(ChuteTileEntity.java:106)
	at net.minecraft.class_2818.method_12007(class_2818.java:366)
	at fi.dy.masa.litematica.world.ChunkSchematic.method_12010(ChunkSchematic.java:123)
	at fi.dy.masa.litematica.world.WorldSchematic.method_8652(WorldSchematic.java:136)
	at fi.dy.masa.litematica.materials.MaterialCache.getItemForStateFromWorld(MaterialCache.java:95)
	at fi.dy.masa.litematica.materials.MaterialCache.getRequiredBuildItemForState(MaterialCache.java:71)
	at fi.dy.masa.litematica.materials.MaterialCache.getRequiredBuildItemForState(MaterialCache.java:62)
	at fi.dy.masa.litematica.materials.MaterialListUtils.convertStatesToStacks(MaterialListUtils.java:110)
	at fi.dy.masa.litematica.materials.MaterialListUtils.getMaterialList(MaterialListUtils.java:73)
	at fi.dy.masa.litematica.materials.MaterialListUtils.createMaterialListFor(MaterialListUtils.java:55)
	at fi.dy.masa.litematica.materials.MaterialListSchematic.reCreateMaterialList(MaterialListSchematic.java:34)
	at fi.dy.masa.litematica.materials.MaterialListSchematic.<init>(MaterialListSchematic.java:27)
	at fi.dy.masa.litematica.materials.MaterialListSchematic.<init>(MaterialListSchematic.java:15)
	at fi.dy.masa.litematica.gui.GuiSchematicLoad$ButtonListener.actionPerformedWithButton(GuiSchematicLoad.java:204)
	at fi.dy.masa.malilib.gui.button.ButtonBase.onMouseClickedImpl(ButtonBase.java:81)
	at fi.dy.masa.malilib.gui.widgets.WidgetBase.onMouseClicked(WidgetBase.java:92)
	at fi.dy.masa.malilib.gui.GuiBase.onMouseClicked(GuiBase.java:270)
	at fi.dy.masa.malilib.gui.GuiListBase.onMouseClicked(GuiListBase.java:92)
	at fi.dy.masa.malilib.gui.GuiBase.method_25402(GuiBase.java:212)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:204)

-- Affected screen --
Details:
	Screen name: fi.dy.masa.litematica.gui.GuiSchematicLoad
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:204)
	at net.minecraft.class_1041.method_15998(class_1041.java:315)
	at net.minecraft.class_310.method_1523(class_310.java:1205)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Solrac_Pq'/15, l='ClientLevel', x=-19.16, y=-43.79, z=13.04]]
	Chunk stats: 1024, 613
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 412337 game time, 42989 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Create Legacy Copper

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 17, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1687475752 bytes (1609 MiB) / 3221225472 bytes (3072 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Virtual memory max (MB): 10420.36
	Virtual memory used (MB): 8071.72
	Swap memory total (MB): 4352.00
	Swap memory used (MB): 1260.59
	JVM Flags: 9 total; -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+IgnoreUnrecognizedVMOptions -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		architectury: Architectury 6.3.56
		cardinal-components-base: Cardinal Components API (base) 5.0.2
		cardinal-components-entity: Cardinal Components API (entities) 5.0.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		create: Create 0.5.0g-791+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.5.0
			flywheel: Flywheel 0.6.8-1
			forgeconfigapiport: Forge Config API Port 4.2.6
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			noindium: No Indium? 1.1.0+1.19
			porting_lib: Porting Lib 2.0.612+1.19.2
				porting_lib_base: Porting Lib Base 2.0.612+1.19.2
					com_github_llamalad7_mixinextras: MixinExtras 0.1.1
					mm: Manningham Mills 2.3
					serialization_hooks: Serialization Hooks 0.3.26
				porting_lib_entity: Porting Lib Entity 2.0.612+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.0.612+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.0.612+1.19.2
				porting_lib_models: Porting Lib Models 2.0.612+1.19.2
				porting_lib_networking: Porting Lib Networking 2.0.612+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.0.612+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.0.612+1.19.2
				porting_lib_tags: Porting Lib Tags 2.0.612+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.0.612+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.0.612+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.0.612+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.0.612+1.19.2
							porting_lib_constants: Porting Lib Constants 2.0.612+1.19.2
						porting_lib_common: Porting Lib Common 2.0.612+1.19.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.44-MC1.19.2
		fabric-api: Fabric API 0.68.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.13+0d0f210290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
			fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.22+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.3+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.38+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.3+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.3+93d8cb8290
			efabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.2+ad31814d90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.31+6eb9a2a190
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.35+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.23+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.21+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.9+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.12+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.20+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.19+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.8+3b1d070f90
			fabric-networking-v0: Fabric Networking (v0) 0.3.25+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.2+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.29+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.1.0+e7aeff4590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.17+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.22+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.25+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.1+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.1+0d0f210290
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.29+0d0f210290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.4+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.1+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.22+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
		fabricloader: Fabric Loader 0.14.12
		indium: Indium 1.0.9+mc1.19.2
		iris: Iris 1.4.3
			io_github_douira_glsl-transformer: glsl-transformer 1.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		java: Java HotSpot(TM) 64-Bit Server VM 17
		litematica: Litematica 0.12.5
		lod: Distant Horizons 1.6.9a
		malilib: MaLiLib 0.13.0
		minecraft: Minecraft 1.19.2
		minihud: MiniHUD 0.23.3
		modmenu: Mod Menu 4.1.0
		roughlyenoughitems: Roughly Enough Items 9.1.574
			error_notifier: Error Notifier 1.0.9
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		travelersbackpack: Traveler's Backpack 1.19.2-8.2.7
		tweakeroo: Tweakeroo 0.14.3
		wi_zoom: WI Zoom 1.4-MC1.19.2
		xaerominimap: Xaero's Minimap 22.16.3
		xaeroworldmap: Xaero's World Map 1.28.4
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.14.12-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) HD Graphics 4600 GL version 3.2.0 - Build 10.18.14.4264, Intel
	Window size: 1600x837
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, Create Legacy Copper
	Current Language: Español (España)
	CPU: 4x Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz
	Server Running: true

**Comment by kosma** [comment]
This is an issue with Create.

**Comment by SolracPq** [comment]
So it is an incompatibility when generating Create Mod blocks with Litematica? Or can I try a previous variant of the same version that I have?
