### ISSUE TITLE
Incompatible mod set

### ISSUE THREAD

**Issue by NotXolex** [maruohon/litematica#641]
Every time I try to load Litematica on 1.19.2 it gives me this error message
```
@''Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set! A potential solution has been determined:
- Install malilib, any 0.13.x version.

Unmet dependency listing:
- Mod 'Litematica' (litematica) 0.12.6 requires any 0.13.x version of malilib, which is missing!

at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)''
```

Does anyone know how to fix this?

*(Edited by masa to not have the entire text in the title, and the issue template untouched in the message >_>)*

**Comment by rycbar0** [comment]
have you tryed installing malilib?

**Comment by kosma** [comment]
Dear friend, please read the error message:

```
Mod 'Litematica' (litematica) 0.12.6 requires any 0.13.x version of malilib, which is missing! at 
Install malilib, any 0.13.x version.
```
