### ISSUE TITLE
conflict with "Minecraft physics mod"

### ISSUE THREAD

**Issue by sosiska-killer-of** [maruohon/litematica#643]
whenever killing a entity with the mod "minecraft physics mod" by Haubna the game crashes if this mod is installed
here is the error:

java.lang.ClassCastException: class fi.dy.masa.litematica.world.WorldSchematic cannot be cast to class net.minecraft.class_638 (fi.dy.masa.litematica.world.WorldSchematic and net.minecraft.class_638 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6a396c1e)
    at net.diebuddies.physics.snow.SnowWorld.applyEntitySnowTracks(SnowWorld.java:273)
    at net.diebuddies.physics.snow.SnowWorld.update(SnowWorld.java:96)
    at net.diebuddies.physics.PhysicsWorld.update(PhysicsWorld.java:168)
    at net.minecraft.class_757.handler$bgo000$render(class_757.java:4211)
    at net.minecraft.class_757.method_3192(class_757.java)
    at net.minecraft.class_310.method_1523(class_310.java:1193)
    at net.minecraft.class_310.method_1514(class_310.java:781)
    at net.minecraft.client.main.Main.method_44604(Main.java:244)
    at net.minecraft.client.main.Main.main(Main.java:51)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by maruohon** [comment]
I don't know how/from where they are getting my schematic world reference, but they shouldn't be using it for anything. They should discard it at least on the basis that it doesn't even satisfy `instanceof ClientWorld`. There is nothing I can do from my side for this.

**Comment by haubna** [comment]
It was due to a mixin into the EntityRenderDispatcher (for offsetting entities by the ocean waves). Fixed now and sorry for the inconvenience! Issue can be closed.

**Comment by maruohon** [comment]
Ok, thank you!
