### ISSUE TITLE
Crashes when loading world

### ISSUE THREAD

**Issue by UsernameNotActive** [maruohon/litematica#661]
The game crashes when joining a world. Based off the crash report it seems that it is because litematica has some problems with modded biomes.

Mod Version: Litematica 0.13.1

Crash report:
java.lang.IllegalStateException: Errors during registry creation
	at net.minecraft.class_7877$class_7878.method_46798(class_7877.java:137)
	at net.minecraft.class_7877.method_46780(class_7877.java:265)
	at net.minecraft.class_7887.method_46817(class_7887.java:84)
	at fi.dy.masa.litematica.world.SchematicWorldHandler.createSchematicWorld(SchematicWorldHandler.java:40)
	at fi.dy.masa.litematica.world.SchematicWorldHandler.getSchematicWorld(SchematicWorldHandler.java:25)
	at fi.dy.masa.litematica.util.RayTraceUtils.traceToSchematicWorld(RayTraceUtils.java:339)
	at fi.dy.masa.litematica.util.RayTraceUtils.getGenericTrace(RayTraceUtils.java:366)
	at fi.dy.masa.litematica.render.OverlayRenderer.renderHoverInfo(OverlayRenderer.java:462)
	at fi.dy.masa.litematica.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:52)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:68)
	at net.minecraft.class_329.handler$bpc000$onGameOverlayPost(class_329.java:3490)
	at net.minecraft.class_329.method_1753(class_329.java:396)
	at net.minecraft.class_757.method_3192(class_757.java:910)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:cypress_wetlands]
		at net.minecraft.class_7877$class_7878.method_46797(class_7877.java:128)
		at net.minecraft.class_7877.method_46780(class_7877.java:264)
		... 18 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:mixed_forest]
		at net.minecraft.class_7877$class_7878.method_46797(class_7877.java:128)
		at net.minecraft.class_7877.method_46780(class_7877.java:264)
		... 18 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:jellyfish_caves]
		at net.minecraft.class_7877$class_7878.method_46797(class_7877.java:128)
		at net.minecraft.class_7877.method_46780(class_7877.java:264)
		... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_7877$class_7878.method_46798(class_7877.java:137)
	at net.minecraft.class_7877.method_46780(class_7877.java:265)
	at net.minecraft.class_7887.method_46817(class_7887.java:84)
	at fi.dy.masa.litematica.world.SchematicWorldHandler.createSchematicWorld(SchematicWorldHandler.java:40)
	at fi.dy.masa.litematica.world.SchematicWorldHandler.getSchematicWorld(SchematicWorldHandler.java:25)
	at fi.dy.masa.litematica.util.RayTraceUtils.traceToSchematicWorld(RayTraceUtils.java:339)
	at fi.dy.masa.litematica.util.RayTraceUtils.getGenericTrace(RayTraceUtils.java:366)
	at fi.dy.masa.litematica.render.OverlayRenderer.renderHoverInfo(OverlayRenderer.java:462)
	at fi.dy.masa.litematica.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:52)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:68)
	at net.minecraft.class_329.handler$bpc000$onGameOverlayPost(class_329.java:3490)
	at net.minecraft.class_329.method_1753(class_329.java:396)

-- Affected level --
Details:
	All players: 1 total; [class_746['Unkillablegaming'/121, l='ClientLevel', x=-154.13, y=79.00, z=238.57]]
	Chunk stats: 1024, 611
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,0), Section: (at 0,0,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 705655 game time, 1034701 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:805)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Aculoss** [comment]
Remove wilder wild and try again

**Comment by UsernameNotActive** [comment]
It works without the wilder wild mod

**Comment by Zyald** [comment]
> It works without the wilder wild mod

did you ever find a fix?

**Comment by maruohon** [comment]
@Zyald Mod version 0.14.3 for MC 1.19.4 should have a fix for this. Which version are you using, and do you get the same stack trace?

**Comment by Zyald** [comment]
@maruohon I found out roughly enough resources was causing it to not work
