### ISSUE TITLE
 error loading schematic

### ISSUE THREAD

**Issue by pedro4666** [maruohon/litematica#677]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-03-18 09:52:50
Description: Rendering screen

java.lang.NoSuchMethodError: 'void com.mojang.blaze3d.systems.RenderSystem.disableTexture()'
	at fi.dy.masa.malilib.render.RenderUtils.drawGradientRect(RenderUtils.java:299)
	at fi.dy.masa.malilib.render.RenderUtils.drawHoverText(RenderUtils.java:259)
	at fi.dy.masa.malilib.gui.widgets.WidgetCheckBox.postRenderHovered(WidgetCheckBox.java:110)
	at fi.dy.masa.malilib.gui.GuiBase.drawHoveredWidget(GuiBase.java:604)
	at fi.dy.masa.malilib.gui.GuiBase.method_25394(GuiBase.java:175)
	at net.minecraft.class_437.method_47413(class_437.java:121)
	at net.minecraft.class_757.method_3192(class_757.java:929)
	at net.minecraft.class_310.method_1523(class_310.java:1200)
	at net.minecraft.class_310.method_1514(class_310.java:789)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:

**Comment by tomalbrc** [comment]
It seems like you're using an old version of litematica for 1.19.4, which is not compatible

**Comment by pedro4666** [comment]
@tomalbrc how do i get the mods for these versions?
