### ISSUE TITLE
Could VulkanMod be supported?

### ISSUE THREAD

**Issue by cloudw233** [maruohon/litematica#815]
**Is your feature request related to a problem? Please describe.**
Vulkanmod has very high performance, but litematica is not compatible with it.

**Describe the solution you'd like**
Fixes compatibility with Vulkan mods.

**Describe alternatives you've considered**
None.
**Additional context**
When I create new world with Litematica and Vulkanmod on 1.20.4,it crashed.
Here's the report
```
[spoiler]游戏核心：A Cube Sugar
启动内存：3195 MB
操作系统：Microsoft Windows 11 专业版 Insider Preview x64
————————————————————
CPU：#012th Gen Intel(R) Core(TM) i7-12700H 
内存：16109
显卡：#0Intel(R) Iris(R) Xe Graphics 
————————————————————
核心路径：C:\Users\QRZ20\Desktop\Minecraft\.minecraft\versions\A Cube Sugar
Java信息：C:\Program Files\Zulu\zulu-18\bin\javaw.exe (Java18.0.1 64 Bit)
BakaXL路径：C:\Users\QRZ20\Desktop\Minecraft\BakaXL_Public_Ver_3.2.3.0.exe
————————————————————
错误日志：
由 BakaXL 记录的 Minecraft 日志流: 
[09:26:32] [main/WARN]: Class path entries reference missing files: C:\Users\QRZ20\Desktop\Minecraft\.minecraft\.minecraft\versions\A Cube Sugar\1.20.4.jar - the game may not load properly!
[09:26:32] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.6
[09:26:32] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[09:26:33] [main/INFO]: Loading 72 mods:
	- fabric-api 0.95.4+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.48+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.12+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.0.2+25e1b4764f
	   |-- fabric-data-generation-api-v1 13.2.1+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.0+44c0f8c64f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.73+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.23+78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.2.31+eabbae364f
	   |-- fabric-loot-api-v2 2.1.7+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.62+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.11+06274a474f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.18+78d798af4f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.52+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.0.33+78d798af4f
	   |-- fabric-rendering-v0 1.1.55+df3654b34f
	   |-- fabric-rendering-v1 3.1.0+0d29db764f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.18+b66dcf784f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.9+e84342304f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- java 18
	- litematica 0.17.0
	- malilib 0.18.0
	- minecraft 1.20.4
	- modmenu 9.0.0
	- vulkanmod 0.3.9
	   |-- org_lwjgl_lwjgl-shaderc 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-linux 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-macos 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-macos-arm64 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-windows 3.3.2
	   |-- org_lwjgl_lwjgl-vma 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-linux 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-macos 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-macos-arm64 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-windows 3.3.2
	   |-- org_lwjgl_lwjgl-vulkan 3.3.2
	   |-- org_lwjgl_lwjgl-vulkan_natives-macos 3.3.2
	   \-- org_lwjgl_lwjgl-vulkan_natives-macos-arm64 3.3.2
[09:26:33] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/QRZ20/Desktop/Minecraft/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[09:26:33] [main/INFO]: Compatibility level set to JAVA_17
[09:26:39] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[09:26:40] [main/INFO]: Completely ignored arguments: [-XX:+UseG1GC]
[09:26:57] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 605 milliseconds
[09:27:03] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[09:27:03] [Render thread/INFO]: Setting user: water_clouds
[09:27:05] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[09:27:06] [Worker-Main-1/INFO]: Checking mod updates...
[09:27:07] [Render thread/INFO]: == VulkanMod ==
[09:27:07] [Render thread/INFO]: Selecting Platform: WIN32
[09:27:07] [Render thread/INFO]: GLFW: 3.4.0 Win32 WGL Null EGL OSMesa VisualC DLL
[09:27:08] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[09:27:13] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, litematica, malilib, modmenu, vulkanmod
[09:27:14] [Worker-Main-7/INFO]: Found unifont_all_no_pua-15.1.04.hex, loading
[09:27:18] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[09:27:18] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[09:27:18] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on æ‰¬å£°å™¨ (Realtek(R) Audio)
[09:27:18] [Render thread/INFO]: Sound engine started
[09:27:18] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[09:27:20] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[09:27:20] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[09:27:20] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[09:27:20] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[09:27:20] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[09:27:20] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[09:27:20] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[09:27:20] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[09:27:21] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[09:27:21] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[09:27:21] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[09:27:21] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[09:38:12] [Render thread/INFO]: Loaded 7 recipes
[09:38:13] [Render thread/INFO]: Loaded 1271 advancements
[09:38:31] [Render thread/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 1.807 ms
[09:38:31] [Server thread/INFO]: Starting integrated minecraft server version 1.20.4
[09:38:31] [Server thread/INFO]: Generating keypair
[09:38:34] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[09:38:36] [Render thread/INFO]: å‡†å¤‡ç”ŸæˆåŒºåŸŸä¸­ï¼š0%
[09:38:36] [Render thread/INFO]: å‡†å¤‡ç”ŸæˆåŒºåŸŸä¸­ï¼š0%
[09:38:36] [Render thread/INFO]: å‡†å¤‡ç”ŸæˆåŒºåŸŸä¸­ï¼š0%
[09:38:36] [Render thread/INFO]: å‡†å¤‡ç”ŸæˆåŒºåŸŸä¸­ï¼š0%
[09:38:37] [Render thread/INFO]: å‡†å¤‡ç”ŸæˆåŒºåŸŸä¸­ï¼š7%
[09:38:37] [Render thread/INFO]: å‡†å¤‡ç”ŸæˆåŒºåŸŸä¸­ï¼š7%
[09:38:37] [Render thread/INFO]: å‡†å¤‡ç”ŸæˆåŒºåŸŸä¸­ï¼š14%
[09:38:38] [Render thread/INFO]: å‡†å¤‡ç”ŸæˆåŒºåŸŸä¸­ï¼š20%
[09:38:38] [Render thread/INFO]: å‡†å¤‡ç”ŸæˆåŒºåŸŸä¸­ï¼š38%
[09:38:39] [Render thread/INFO]: å‡†å¤‡ç”ŸæˆåŒºåŸŸä¸­ï¼š60%
[09:38:39] [Render thread/INFO]: å‡†å¤‡ç”ŸæˆåŒºåŸŸä¸­ï¼š69%
[09:38:40] [Render thread/INFO]: å‡†å¤‡ç”ŸæˆåŒºåŸŸä¸­ï¼š69%
[09:38:40] [Render thread/INFO]: å‡†å¤‡ç”ŸæˆåŒºåŸŸä¸­ï¼š83%
[09:38:41] [Render thread/INFO]: Time elapsed: 6450 ms
[09:38:41] [Server thread/INFO]: Changing view distance to 12, from 10
[09:38:41] [Server thread/INFO]: Changing simulation distance to 12, from 0
[09:38:44] [Server thread/INFO]: water_clouds[local:E:fa28583a] logged in with entity id 15 at (5.5, -60.0, -0.5)
[09:38:44] [Server thread/INFO]: water_cloudsåŠ å…¥äº†æ¸¸æˆ
[09:38:45] [Render thread/INFO]: Using 3 total BufferBuilder caches
[09:38:45] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[09:38:45] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[09:38:45] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[09:38:45] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[09:38:45] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[09:38:45] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[09:38:45] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[09:38:45] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[09:38:46] [Render thread/INFO]: Loaded 2 advancements
[09:38:48] [Render thread/ERROR]: Unreported exception thrown!
java.lang.RuntimeException: unknown drawMode: DEBUG_LINES
	at net.vulkanmod.vulkan.Drawer.draw(Drawer.java:95) ~[VulkanMod_1.20.4-0.3.9.jar:?]
	at net.minecraft.class_286.method_43433(class_286.java:546) ~[client-intermediary.jar:?]
	at net.minecraft.class_289.method_1350(class_289.java:41) ~[client-intermediary.jar:?]
	at fi.dy.masa.litematica.render.RenderUtils.renderBlockOutlineOverlapping(RenderUtils.java:178) ~[litematica-fabric-1.20.4-0.17.0.jar:?]
	at fi.dy.masa.litematica.render.OverlayRenderer.renderSelectionBox(OverlayRenderer.java:329) ~[litematica-fabric-1.20.4-0.17.0.jar:?]
	at fi.dy.masa.litematica.render.OverlayRenderer.renderBoxes(OverlayRenderer.java:155) ~[litematica-fabric-1.20.4-0.17.0.jar:?]
	at fi.dy.masa.litematica.event.RenderHandler.onRenderWorldLast(RenderHandler.java:28) ~[litematica-fabric-1.20.4-0.17.0.jar:?]
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderWorldLast(RenderEventHandler.java:114) ~[malilib-fabric-1.20.4-0.18.0.jar:?]
	at net.minecraft.class_761.handler$zno000$malilib$onRenderWorldLastNormal(class_761.java:4681) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1318) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1098) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:866) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1327) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
[09:38:49] [Server thread/INFO]: Stopping server
[09:38:49] [Server thread/INFO]: Saving players
[09:38:49] [Server thread/INFO]: Saving worlds
[09:38:51] [Server thread/INFO]: Saving chunks for level 'ServerLevel[æ–°çš„ä¸–ç•Œ]'/minecraft:overworld
[09:38:52] [Server thread/INFO]: Saving chunks for level 'ServerLevel[æ–°çš„ä¸–ç•Œ]'/minecraft:the_end
[09:38:52] [Server thread/INFO]: Saving chunks for level 'ServerLevel[æ–°çš„ä¸–ç•Œ]'/minecraft:the_nether
[09:38:52] [Server thread/INFO]: ThreadedAnvilChunkStorage (æ–°çš„ä¸–ç•Œ): All chunks are saved
[09:38:52] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[09:38:52] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[09:38:52] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff8c637fbf2, pid=28264, tid=30432
#
# JRE version: OpenJDK Runtime Environment Zulu18.30+11-CA (18.0.1+10) (build 18.0.1+10)
# Java VM: OpenJDK 64-Bit Server VM Zulu18.30+11-CA (18.0.1+10, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [igvk64.dll+0x36fbf2]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\QRZ20\Desktop\Minecraft\.minecraft\versions\A Cube Sugar\hs_err_pid28264.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

[/spoiler]
```

**Comment by IAmREGE** [comment]
我用的HMCL的渲染器选项“Vulkan”，没有加VlukanMod，没观测到崩溃现象（

**Comment by Syntrait** [comment]
Is there any progress on this, with Mojang working on Vulkan?
