### ISSUE TITLE
litematica 1.20.6

### ISSUE THREAD

**Issue by bullerjo1** [maruohon/litematica#861]
will not work. have tried everything
![image2](https://github.com/maruohon/litematica/assets/144950982/25100332-43dd-480e-9dea-3b8a9b460f2e)
![image](https://github.com/maruohon/litematica/assets/144950982/6bd5c09c-b3a6-486c-b686-d6892e5f2ad8)
[log]
[21:51:13] [main/INFO]: Loading Minecraft 1.20.6 with Fabric Loader 0.15.11
[21:51:13] [main/WARN]: Mod resolution failed
[21:51:13] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED litematica 0.17.3 {depends minecraft @ [>=1.20.3 <=1.20.4]}, ROOT_FORCELOAD_SINGLE litematica 0.17.3]
[21:51:13] [main/INFO]: Reason: [HARD_DEP litematica 0.17.3 {depends minecraft @ [>=1.20.3 <=1.20.4]}]
[21:51:13] [main/INFO]: Fix: add [], remove [], replace [[litematica 0.17.3] -> add:litematica 1 ([(-∞,∞)])]
[21:51:13] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Litematica' (litematica) 0.17.3 with any version that is compatible with:
		 - minecraft 1.20.6
More details:
	 - Mod 'Litematica' (litematica) 0.17.3 requires any version between 1.20.3 (inclusive) and 1.20.4 (inclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.6!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]

**Comment by sakura-ryoko** [comment]
You downloaded the ZIP file of the branch and not the JAR file, also you still have the 1.20.4 version.

**Comment by bullerjo1** [comment]
mit mc strat op men litematica vil ikke virker
![image1](https://github.com/maruohon/litematica/assets/144950982/235c0ec0-ac68-4732-8055-0f387cd66e88)
[log]
[21:59:30] [main/INFO]: Loading Minecraft 1.20.6 with Fabric Loader 0.15.11
[21:59:30] [main/INFO]: Loading 8 mods:
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 21
	- malilib 0.19.0
	   |-- fabric-api-base 0.4.40+80f8cf510d
	   |-- fabric-networking-api-v1 4.0.8+bd46f3a00d
	   \-- fabric-resource-loader-v0 1.0.5+c5f2432c0d
	- minecraft 1.20.6
[21:59:30] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/*****/curseforge/minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[21:59:30] [main/INFO]: Compatibility level set to JAVA_17
[21:59:40] [Datafixer Bootstrap/INFO]: 222 Datafixer optimizations took 1195 milliseconds
[21:59:44] [Render thread/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[21:59:44] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[21:59:44] [Render thread/INFO]: Setting user: bullerjo1
[21:59:45] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
[21:59:48] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, fabric-api-base, fabric-networking-api-v1, fabric-resource-loader-v0, fabricloader, malilib, file/Faithful 64x - Release 4.zip
[21:59:48] [Worker-Main-3/INFO]: Found unifont_all_no_pua-15.1.04.hex, loading
[21:59:49] [Worker-Main-5/INFO]: Found unifont_jp_patch-15.1.04.hex, loading
[21:59:51] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[21:59:51] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[21:59:51] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Højttalere (Logitech Z337 Stereo)
[21:59:51] [Render thread/INFO]: Sound engine started
[21:59:51] [Render thread/INFO]: Created: 4096x2048x4 minecraft:textures/atlas/blocks.png-atlas
[21:59:51] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/signs.png-atlas
[21:59:51] [Render thread/INFO]: Created: 2048x2048x4 minecraft:textures/atlas/shield_patterns.png-atlas
[21:59:51] [Render thread/INFO]: Created: 2048x2048x4 minecraft:textures/atlas/banner_patterns.png-atlas
[21:59:51] [Render thread/INFO]: Created: 4096x4096x4 minecraft:textures/atlas/armor_trims.png-atlas
[21:59:51] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/decorated_pot.png-atlas
[21:59:51] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/chest.png-atlas
[21:59:51] [Render thread/INFO]: Created: 2048x1024x4 minecraft:textures/atlas/beds.png-atlas
[21:59:51] [Render thread/INFO]: Created: 2048x1024x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[21:59:52] [Render thread/INFO]: Created: 2048x1024x0 minecraft:textures/atlas/particles.png-atlas
[21:59:52] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/paintings.png-atlas
[21:59:52] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/mob_effects.png-atlas
[21:59:52] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/map_decorations.png-atlas
[21:59:52] [Render thread/INFO]: Created: 4096x2048x0 minecraft:textures/atlas/gui.png-atlas
[21:59:52] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[22:00:11] [Render thread/WARN]: Missing data pack fabric-convention-tags-v2
[22:00:13] [Render thread/INFO]: Loaded 1175 recipes
[22:00:13] [Render thread/INFO]: Loaded 1276 advancements
[22:00:14] [Server thread/INFO]: Starting integrated minecraft server version 1.20.6
[22:00:14] [Server thread/INFO]: Generating keypair
[22:00:14] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[22:00:15] [Render thread/INFO]: Preparing spawn area: 0%
[22:00:15] [Render thread/INFO]: Preparing spawn area: 0%
[22:00:15] [Render thread/INFO]: Preparing spawn area: 32%
[22:00:15] [Render thread/INFO]: Time elapsed: 1058 ms
[22:00:15] [Server thread/INFO]: Changing view distance to 12, from 10
[22:00:15] [Server thread/INFO]: Changing simulation distance to 12, from 0
[22:00:16] [Server thread/INFO]: bullerjo1[local:E:29cc3e8b] logged in with entity id 1 at (-3.75273985148025, -60.0, -2.32688570591091)
[22:00:17] [Server thread/INFO]: bullerjo1 joined the game
[22:00:17] [Render thread/INFO]: Loaded 12 advancements
[22:00:25] [Server thread/INFO]: Saving and pausing game...
[22:00:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[22:00:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[22:00:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[22:00:29] [Render thread/INFO]: Stopping!
[22:00:30] [Server thread/INFO]: bullerjo1 lost connection: Disconnected
[22:00:30] [Server thread/INFO]: bullerjo1 left the game
[22:00:30] [Server thread/INFO]: Stopping singleplayer server as player logged out
[22:00:30] [Server thread/INFO]: Stopping server
[22:00:30] [Server thread/INFO]: Saving players
[22:00:30] [Server thread/INFO]: Saving worlds
[22:00:30] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[22:00:30] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[22:00:30] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[22:00:30] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[22:00:30] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[22:00:30] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[22:00:30] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

**Comment by sakura-ryoko** [comment]
Use this
https://github.com/sakura-ryoko/litematica/releases/download/1.20.6-0.18.0/litematica-fabric-1.20.6-0.18.0.jar

**Comment by bullerjo1** [comment]
it works now
thx
